include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    - lib/**.g.dart

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    unawaited_futures: true 