name: datadog_common_test
description: Common helpers for testing Datadog libraries. Not meant to be a published package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ">=0.13.4 <2.0.0"
  json_annotation: ^4.9.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  json_serializable: '>=6.7.0 <6.10.0'
  build_runner: ^2.1.10
