// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// TODO(RUM-18092): Remove this suppression along with the rest of the workaround
// in this file once v4's bindings are regenerated with jnigen >= 0.17.0.
//
// `JObject.reference` is marked `@internal` by package:jni, but reaching for it
// is the only way to get a `Finalizable`-typed handle on a JNI object, which is
// required for the keep-alive documented on [getContext] below. The bindings
// generated by `jnigen` suppress the same warning for the same reason.
// ignore_for_file: invalid_use_of_internal_member

import 'package:jni/jni.dart';

import '../../datadog_internal.dart';
import 'datadog_android_bridge.dart' as bridge;

class AndroidDatadogFlutterPlugin {
  static final JString _javaRumKey = JString.fromString('rum');
  static final JString _javaSessionId = JString.fromString('session_id');

  /// Reads the current Datadog context from the Android SDK over JNI.
  ///
  /// Every object used as the receiver of a JNI call is held in a local whose
  /// static type is [JReference], which implements `Finalizable`. This is load
  /// bearing, not stylistic: a local of a `Finalizable` type is guaranteed to
  /// stay alive for its whole scope, which stops the GC from running the
  /// finalizer that deletes the underlying JNI global reference.
  ///
  /// Without it, a receiver can be collected -- and its global reference
  /// deleted -- while the JNI call using it is still in flight, which faults
  /// inside ART rather than throwing. `jnigen` only applies this protection to
  /// method *arguments*; it did not apply it to receivers until 0.17.0, which
  /// we cannot take on v3. See https://dartbug.com/63348.
  ///
  /// The same reason is why each reference is released explicitly instead of
  /// being left to the finalizer: fewer abandoned references means less
  /// finalizer traffic on the request path.
  ///
  // TODO(RUM-18092): jnigen 0.17.0 hoists the receiver itself, so on v4 this can
  // go back to the plain chained form -- `javaContext.getUserInfo().getId()` and
  // friends -- and drop every `*Ref` local. Note that as of writing, v4's
  // checked-in bindings were still generated with jnigen 0.16.0 and do *not*
  // have the fix, so do not delete this until they have been regenerated and
  // `grep selfRef` finds hits in the generated bindings.
  static DatadogContext? getContext() {
    // Note that `Companion` allocates a new global reference on each access,
    // so it needs the same treatment as any other object.
    final companion = bridge.DatadogSdkPlugin.Companion;
    final companionRef = companion.reference;
    final javaContext = companion.getCoreContext();
    companionRef.release();
    if (javaContext == null) return null;
    final contextRef = javaContext.reference;

    String? sessionId;
    final featuresContext = javaContext.getFeaturesContext();
    final featuresContextRef = featuresContext.reference;
    final rumContext = featuresContext[_javaRumKey];
    featuresContextRef.release();
    if (rumContext != null) {
      final rumContextRef = rumContext.reference;
      final javaSessionId = rumContext[_javaSessionId];
      rumContextRef.release();
      if (javaSessionId != null) {
        final javaSessionIdRef = javaSessionId.reference;
        sessionId = javaSessionId.toString();
        javaSessionIdRef.release();
      }
    }

    final accountInfo = javaContext.getAccountInfo();
    final accountInfoRef = accountInfo?.reference;
    final javaAccountId = accountInfo?.getId();
    accountInfoRef?.release();
    final javaAccountIdRef = javaAccountId?.reference;
    final accountId = javaAccountId?.toDartString();
    javaAccountIdRef?.release();

    final userInfo = javaContext.getUserInfo();
    final userInfoRef = userInfo.reference;
    final javaUserId = userInfo.getId();
    userInfoRef.release();
    final javaUserIdRef = javaUserId?.reference;
    final userId = javaUserId?.toDartString();
    javaUserIdRef?.release();

    contextRef.release();

    return DatadogContext(
      sessionId: sessionId,
      accountId: accountId,
      userId: userId,
    );
  }
}
