// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.datadoghq.flutter.DatadogRumEventMapper$EventMapper`
class DatadogRumEventMapper$EventMapper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogRumEventMapper$EventMapper> $type;

  @jni$_.internal
  DatadogRumEventMapper$EventMapper.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogRumEventMapper$EventMapper',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogRumEventMapper$EventMapper$NullableType();
  static const type = $DatadogRumEventMapper$EventMapper$Type();
  static final _id_mapViewEvent = _class.instanceMethodId(
    r'mapViewEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapViewEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapViewEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapViewEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapViewEvent(
      reference.pointer,
      _id_mapViewEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_mapActionEvent = _class.instanceMethodId(
    r'mapActionEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapActionEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapActionEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapActionEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapActionEvent(
      reference.pointer,
      _id_mapActionEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_mapResourceEvent = _class.instanceMethodId(
    r'mapResourceEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapResourceEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapResourceEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapResourceEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapResourceEvent(
      reference.pointer,
      _id_mapResourceEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_mapErrorEvent = _class.instanceMethodId(
    r'mapErrorEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapErrorEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapErrorEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapErrorEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapErrorEvent(
      reference.pointer,
      _id_mapErrorEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_mapLongTaskEvent = _class.instanceMethodId(
    r'mapLongTaskEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapLongTaskEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapLongTaskEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapLongTaskEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapLongTaskEvent(
      reference.pointer,
      _id_mapLongTaskEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $DatadogRumEventMapper$EventMapper> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'mapViewEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapViewEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'mapActionEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapActionEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'mapResourceEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapResourceEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'mapErrorEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapErrorEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'mapLongTaskEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapLongTaskEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $DatadogRumEventMapper$EventMapper $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.datadoghq.flutter.DatadogRumEventMapper$EventMapper',
      $p,
      _$invokePointer,
      [],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory DatadogRumEventMapper$EventMapper.implement(
    $DatadogRumEventMapper$EventMapper $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return DatadogRumEventMapper$EventMapper.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $DatadogRumEventMapper$EventMapper {
  factory $DatadogRumEventMapper$EventMapper({
    required jni$_.JString? Function(jni$_.JString string) mapViewEvent,
    required jni$_.JString? Function(jni$_.JString string) mapActionEvent,
    required jni$_.JString? Function(jni$_.JString string) mapResourceEvent,
    required jni$_.JString? Function(jni$_.JString string) mapErrorEvent,
    required jni$_.JString? Function(jni$_.JString string) mapLongTaskEvent,
  }) = _$DatadogRumEventMapper$EventMapper;

  jni$_.JString? mapViewEvent(jni$_.JString string);
  jni$_.JString? mapActionEvent(jni$_.JString string);
  jni$_.JString? mapResourceEvent(jni$_.JString string);
  jni$_.JString? mapErrorEvent(jni$_.JString string);
  jni$_.JString? mapLongTaskEvent(jni$_.JString string);
}

final class _$DatadogRumEventMapper$EventMapper
    with $DatadogRumEventMapper$EventMapper {
  _$DatadogRumEventMapper$EventMapper({
    required jni$_.JString? Function(jni$_.JString string) mapViewEvent,
    required jni$_.JString? Function(jni$_.JString string) mapActionEvent,
    required jni$_.JString? Function(jni$_.JString string) mapResourceEvent,
    required jni$_.JString? Function(jni$_.JString string) mapErrorEvent,
    required jni$_.JString? Function(jni$_.JString string) mapLongTaskEvent,
  }) : _mapViewEvent = mapViewEvent,
       _mapActionEvent = mapActionEvent,
       _mapResourceEvent = mapResourceEvent,
       _mapErrorEvent = mapErrorEvent,
       _mapLongTaskEvent = mapLongTaskEvent;

  final jni$_.JString? Function(jni$_.JString string) _mapViewEvent;
  final jni$_.JString? Function(jni$_.JString string) _mapActionEvent;
  final jni$_.JString? Function(jni$_.JString string) _mapResourceEvent;
  final jni$_.JString? Function(jni$_.JString string) _mapErrorEvent;
  final jni$_.JString? Function(jni$_.JString string) _mapLongTaskEvent;

  jni$_.JString? mapViewEvent(jni$_.JString string) {
    return _mapViewEvent(string);
  }

  jni$_.JString? mapActionEvent(jni$_.JString string) {
    return _mapActionEvent(string);
  }

  jni$_.JString? mapResourceEvent(jni$_.JString string) {
    return _mapResourceEvent(string);
  }

  jni$_.JString? mapErrorEvent(jni$_.JString string) {
    return _mapErrorEvent(string);
  }

  jni$_.JString? mapLongTaskEvent(jni$_.JString string) {
    return _mapLongTaskEvent(string);
  }
}

final class $DatadogRumEventMapper$EventMapper$NullableType
    extends jni$_.JObjType<DatadogRumEventMapper$EventMapper?> {
  @jni$_.internal
  const $DatadogRumEventMapper$EventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogRumEventMapper$EventMapper? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : DatadogRumEventMapper$EventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumEventMapper$EventMapper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($DatadogRumEventMapper$EventMapper$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($DatadogRumEventMapper$EventMapper$NullableType) &&
        other is $DatadogRumEventMapper$EventMapper$NullableType;
  }
}

final class $DatadogRumEventMapper$EventMapper$Type
    extends jni$_.JObjType<DatadogRumEventMapper$EventMapper> {
  @jni$_.internal
  const $DatadogRumEventMapper$EventMapper$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogRumEventMapper$EventMapper fromReference(jni$_.JReference reference) =>
      DatadogRumEventMapper$EventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumEventMapper$EventMapper?> get nullableType =>
      const $DatadogRumEventMapper$EventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumEventMapper$EventMapper$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumEventMapper$EventMapper$Type) &&
        other is $DatadogRumEventMapper$EventMapper$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogRumEventMapper`
class DatadogRumEventMapper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogRumEventMapper> $type;

  @jni$_.internal
  DatadogRumEventMapper.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogRumEventMapper',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogRumEventMapper$NullableType();
  static const type = $DatadogRumEventMapper$Type();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogRumEventMapper() {
    return DatadogRumEventMapper.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_getEventMapper = _class.instanceMethodId(
    r'getEventMapper',
    r'()Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;',
  );

  static final _getEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.DatadogRumEventMapper$EventMapper getEventMapper()`
  /// The returned object must be released after use, by calling the [release] method.
  DatadogRumEventMapper$EventMapper? getEventMapper() {
    return _getEventMapper(
      reference.pointer,
      _id_getEventMapper as jni$_.JMethodIDPtr,
    ).object<DatadogRumEventMapper$EventMapper?>(
      const $DatadogRumEventMapper$EventMapper$NullableType(),
    );
  }

  static final _id_setEventMapper = _class.instanceMethodId(
    r'setEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;)V',
  );

  static final _setEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setEventMapper(com.datadoghq.flutter.DatadogRumEventMapper$EventMapper eventMapper)`
  void setEventMapper(DatadogRumEventMapper$EventMapper? eventMapper) {
    final _$eventMapper = eventMapper?.reference ?? jni$_.jNullReference;
    _setEventMapper(
      reference.pointer,
      _id_setEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }

  static final _id_attachMappers = _class.instanceMethodId(
    r'attachMappers',
    r'(Ljava/util/Map;Lcom/datadog/android/rum/RumConfiguration$Builder;)Lcom/datadog/android/rum/RumConfiguration$Builder;',
  );

  static final _attachMappers =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final com.datadog.android.rum.RumConfiguration$Builder attachMappers(java.util.Map<java.lang.String, ? extends java.lang.Object> map, com.datadog.android.rum.RumConfiguration$Builder builder)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject attachMappers(
    jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
    jni$_.JObject builder,
  ) {
    final _$map = map.reference;
    final _$builder = builder.reference;
    return _attachMappers(
      reference.pointer,
      _id_attachMappers as jni$_.JMethodIDPtr,
      _$map.pointer,
      _$builder.pointer,
    ).object<jni$_.JObject>(const jni$_.JObjectType());
  }
}

final class $DatadogRumEventMapper$NullableType
    extends jni$_.JObjType<DatadogRumEventMapper?> {
  @jni$_.internal
  const $DatadogRumEventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumEventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogRumEventMapper? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : DatadogRumEventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumEventMapper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumEventMapper$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumEventMapper$NullableType) &&
        other is $DatadogRumEventMapper$NullableType;
  }
}

final class $DatadogRumEventMapper$Type
    extends jni$_.JObjType<DatadogRumEventMapper> {
  @jni$_.internal
  const $DatadogRumEventMapper$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumEventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogRumEventMapper fromReference(jni$_.JReference reference) =>
      DatadogRumEventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumEventMapper?> get nullableType =>
      const $DatadogRumEventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumEventMapper$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumEventMapper$Type) &&
        other is $DatadogRumEventMapper$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogRumPlugin$Companion`
class DatadogRumPlugin$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogRumPlugin$Companion> $type;

  @jni$_.internal
  DatadogRumPlugin$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogRumPlugin$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogRumPlugin$Companion$NullableType();
  static const type = $DatadogRumPlugin$Companion$Type();
  static final _id_setRumEventMapper = _class.instanceMethodId(
    r'setRumEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;)V',
  );

  static final _setRumEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setRumEventMapper(com.datadoghq.flutter.DatadogRumEventMapper$EventMapper eventMapper)`
  void setRumEventMapper(DatadogRumEventMapper$EventMapper eventMapper) {
    final _$eventMapper = eventMapper.reference;
    _setRumEventMapper(
      reference.pointer,
      _id_setRumEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogRumPlugin$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return DatadogRumPlugin$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $DatadogRumPlugin$Companion$NullableType
    extends jni$_.JObjType<DatadogRumPlugin$Companion?> {
  @jni$_.internal
  const $DatadogRumPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  DatadogRumPlugin$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : DatadogRumPlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumPlugin$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumPlugin$Companion$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumPlugin$Companion$NullableType) &&
        other is $DatadogRumPlugin$Companion$NullableType;
  }
}

final class $DatadogRumPlugin$Companion$Type
    extends jni$_.JObjType<DatadogRumPlugin$Companion> {
  @jni$_.internal
  const $DatadogRumPlugin$Companion$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  DatadogRumPlugin$Companion fromReference(jni$_.JReference reference) =>
      DatadogRumPlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumPlugin$Companion?> get nullableType =>
      const $DatadogRumPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumPlugin$Companion$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumPlugin$Companion$Type) &&
        other is $DatadogRumPlugin$Companion$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogRumPlugin`
class DatadogRumPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogRumPlugin> $type;

  @jni$_.internal
  DatadogRumPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogRumPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogRumPlugin$NullableType();
  static const type = $DatadogRumPlugin$Type();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/datadoghq/flutter/DatadogRumPlugin$Companion;',
  );

  /// from: `static public final com.datadoghq.flutter.DatadogRumPlugin$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static DatadogRumPlugin$Companion get Companion =>
      _id_Companion.get(_class, const $DatadogRumPlugin$Companion$Type());

  static final _id_PARAM_AT = _class.staticFieldId(
    r'PARAM_AT',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_AT`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_AT =>
      _id_PARAM_AT.get(_class, const jni$_.JStringType());

  static final _id_PARAM_DURATION = _class.staticFieldId(
    r'PARAM_DURATION',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_DURATION`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_DURATION =>
      _id_PARAM_DURATION.get(_class, const jni$_.JStringType());

  static final _id_PARAM_KEY = _class.staticFieldId(
    r'PARAM_KEY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_KEY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_KEY =>
      _id_PARAM_KEY.get(_class, const jni$_.JStringType());

  static final _id_PARAM_VALUE = _class.staticFieldId(
    r'PARAM_VALUE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_VALUE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_VALUE =>
      _id_PARAM_VALUE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_NAME = _class.staticFieldId(
    r'PARAM_NAME',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_NAME`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_NAME =>
      _id_PARAM_NAME.get(_class, const jni$_.JStringType());

  static final _id_PARAM_ATTRIBUTES = _class.staticFieldId(
    r'PARAM_ATTRIBUTES',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_ATTRIBUTES`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_ATTRIBUTES =>
      _id_PARAM_ATTRIBUTES.get(_class, const jni$_.JStringType());

  static final _id_PARAM_URL = _class.staticFieldId(
    r'PARAM_URL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_URL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_URL =>
      _id_PARAM_URL.get(_class, const jni$_.JStringType());

  static final _id_PARAM_HTTP_METHOD = _class.staticFieldId(
    r'PARAM_HTTP_METHOD',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_HTTP_METHOD`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_HTTP_METHOD =>
      _id_PARAM_HTTP_METHOD.get(_class, const jni$_.JStringType());

  static final _id_PARAM_KIND = _class.staticFieldId(
    r'PARAM_KIND',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_KIND`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_KIND =>
      _id_PARAM_KIND.get(_class, const jni$_.JStringType());

  static final _id_PARAM_STATUS_CODE = _class.staticFieldId(
    r'PARAM_STATUS_CODE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_STATUS_CODE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_STATUS_CODE =>
      _id_PARAM_STATUS_CODE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_SIZE = _class.staticFieldId(
    r'PARAM_SIZE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_SIZE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_SIZE =>
      _id_PARAM_SIZE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_MESSAGE = _class.staticFieldId(
    r'PARAM_MESSAGE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_MESSAGE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_MESSAGE =>
      _id_PARAM_MESSAGE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_SOURCE = _class.staticFieldId(
    r'PARAM_SOURCE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_SOURCE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_SOURCE =>
      _id_PARAM_SOURCE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_STACK_TRACE = _class.staticFieldId(
    r'PARAM_STACK_TRACE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_STACK_TRACE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_STACK_TRACE =>
      _id_PARAM_STACK_TRACE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_ERROR_TYPE = _class.staticFieldId(
    r'PARAM_ERROR_TYPE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_ERROR_TYPE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_ERROR_TYPE =>
      _id_PARAM_ERROR_TYPE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_TYPE = _class.staticFieldId(
    r'PARAM_TYPE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_TYPE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_TYPE =>
      _id_PARAM_TYPE.get(_class, const jni$_.JStringType());

  static final _id_PARAM_BUILD_TIMES = _class.staticFieldId(
    r'PARAM_BUILD_TIMES',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_BUILD_TIMES`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_BUILD_TIMES =>
      _id_PARAM_BUILD_TIMES.get(_class, const jni$_.JStringType());

  static final _id_PARAM_RASTER_TIMES = _class.staticFieldId(
    r'PARAM_RASTER_TIMES',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_RASTER_TIMES`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_RASTER_TIMES =>
      _id_PARAM_RASTER_TIMES.get(_class, const jni$_.JStringType());

  static final _id_PARAM_OVERWRITE = _class.staticFieldId(
    r'PARAM_OVERWRITE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARAM_OVERWRITE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get PARAM_OVERWRITE =>
      _id_PARAM_OVERWRITE.get(_class, const jni$_.JStringType());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogRumPlugin() {
    return DatadogRumPlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_getRum = _class.instanceMethodId(
    r'getRum',
    r'()Lcom/datadog/android/rum/RumMonitor;',
  );

  static final _getRum =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadog.android.rum.RumMonitor getRum()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getRum() {
    return _getRum(
      reference.pointer,
      _id_getRum as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_getTelemetryOverrides = _class.instanceMethodId(
    r'getTelemetryOverrides',
    r'()Lcom/datadoghq/flutter/DatadogSdkPlugin$ConfigurationTelemetryOverrides;',
  );

  static final _getTelemetryOverrides =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.DatadogSdkPlugin$ConfigurationTelemetryOverrides getTelemetryOverrides()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getTelemetryOverrides() {
    return _getTelemetryOverrides(
      reference.pointer,
      _id_getTelemetryOverrides as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_setTelemetryOverrides = _class.instanceMethodId(
    r'setTelemetryOverrides',
    r'(Lcom/datadoghq/flutter/DatadogSdkPlugin$ConfigurationTelemetryOverrides;)V',
  );

  static final _setTelemetryOverrides =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setTelemetryOverrides(com.datadoghq.flutter.DatadogSdkPlugin$ConfigurationTelemetryOverrides configurationTelemetryOverrides)`
  void setTelemetryOverrides(jni$_.JObject? configurationTelemetryOverrides) {
    final _$configurationTelemetryOverrides =
        configurationTelemetryOverrides?.reference ?? jni$_.jNullReference;
    _setTelemetryOverrides(
      reference.pointer,
      _id_setTelemetryOverrides as jni$_.JMethodIDPtr,
      _$configurationTelemetryOverrides.pointer,
    ).check();
  }

  static final _id_attachToEngine = _class.instanceMethodId(
    r'attachToEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _attachToEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void attachToEngine(io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding flutterPluginBinding)`
  void attachToEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _attachToEngine(
      reference.pointer,
      _id_attachToEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_detachFromEngine = _class.instanceMethodId(
    r'detachFromEngine',
    r'()V',
  );

  static final _detachFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final void detachFromEngine()`
  void detachFromEngine() {
    _detachFromEngine(
      reference.pointer,
      _id_detachFromEngine as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_onMethodCall = _class.instanceMethodId(
    r'onMethodCall',
    r'(Lio/flutter/plugin/common/MethodCall;Lio/flutter/plugin/common/MethodChannel$Result;)V',
  );

  static final _onMethodCall =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onMethodCall(io.flutter.plugin.common.MethodCall methodCall, io.flutter.plugin.common.MethodChannel$Result result)`
  void onMethodCall(jni$_.JObject methodCall, jni$_.JObject result) {
    final _$methodCall = methodCall.reference;
    final _$result = result.reference;
    _onMethodCall(
      reference.pointer,
      _id_onMethodCall as jni$_.JMethodIDPtr,
      _$methodCall.pointer,
      _$result.pointer,
    ).check();
  }

  static final _id_attachToExistingSdk = _class.instanceMethodId(
    r'attachToExistingSdk',
    r'(Lcom/datadog/android/rum/RumMonitor;)V',
  );

  static final _attachToExistingSdk =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void attachToExistingSdk(com.datadog.android.rum.RumMonitor rumMonitor)`
  void attachToExistingSdk(jni$_.JObject rumMonitor) {
    final _$rumMonitor = rumMonitor.reference;
    _attachToExistingSdk(
      reference.pointer,
      _id_attachToExistingSdk as jni$_.JMethodIDPtr,
      _$rumMonitor.pointer,
    ).check();
  }

  static final _id_setRumEventMapper = _class.staticMethodId(
    r'setRumEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogRumEventMapper$EventMapper;)V',
  );

  static final _setRumEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void setRumEventMapper(com.datadoghq.flutter.DatadogRumEventMapper$EventMapper eventMapper)`
  static void setRumEventMapper(DatadogRumEventMapper$EventMapper eventMapper) {
    final _$eventMapper = eventMapper.reference;
    _setRumEventMapper(
      _class.reference.pointer,
      _id_setRumEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }
}

final class $DatadogRumPlugin$NullableType
    extends jni$_.JObjType<DatadogRumPlugin?> {
  @jni$_.internal
  const $DatadogRumPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumPlugin;';

  @jni$_.internal
  @core$_.override
  DatadogRumPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : DatadogRumPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumPlugin$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumPlugin$NullableType) &&
        other is $DatadogRumPlugin$NullableType;
  }
}

final class $DatadogRumPlugin$Type extends jni$_.JObjType<DatadogRumPlugin> {
  @jni$_.internal
  const $DatadogRumPlugin$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogRumPlugin;';

  @jni$_.internal
  @core$_.override
  DatadogRumPlugin fromReference(jni$_.JReference reference) =>
      DatadogRumPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogRumPlugin?> get nullableType =>
      const $DatadogRumPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogRumPlugin$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogRumPlugin$Type) &&
        other is $DatadogRumPlugin$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogLogsPlugin$Companion`
class DatadogLogsPlugin$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogLogsPlugin$Companion> $type;

  @jni$_.internal
  DatadogLogsPlugin$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogLogsPlugin$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogLogsPlugin$Companion$NullableType();
  static const type = $DatadogLogsPlugin$Companion$Type();
  static final _id_setLogsEventMapper = _class.instanceMethodId(
    r'setLogsEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;)V',
  );

  static final _setLogsEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setLogsEventMapper(com.datadoghq.flutter.DatadogLogEventMapper$EventMapper eventMapper)`
  void setLogsEventMapper(DatadogLogEventMapper$EventMapper eventMapper) {
    final _$eventMapper = eventMapper.reference;
    _setLogsEventMapper(
      reference.pointer,
      _id_setLogsEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogLogsPlugin$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return DatadogLogsPlugin$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $DatadogLogsPlugin$Companion$NullableType
    extends jni$_.JObjType<DatadogLogsPlugin$Companion?> {
  @jni$_.internal
  const $DatadogLogsPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogLogsPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  DatadogLogsPlugin$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : DatadogLogsPlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogsPlugin$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogsPlugin$Companion$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogsPlugin$Companion$NullableType) &&
        other is $DatadogLogsPlugin$Companion$NullableType;
  }
}

final class $DatadogLogsPlugin$Companion$Type
    extends jni$_.JObjType<DatadogLogsPlugin$Companion> {
  @jni$_.internal
  const $DatadogLogsPlugin$Companion$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogLogsPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  DatadogLogsPlugin$Companion fromReference(jni$_.JReference reference) =>
      DatadogLogsPlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogsPlugin$Companion?> get nullableType =>
      const $DatadogLogsPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogsPlugin$Companion$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogsPlugin$Companion$Type) &&
        other is $DatadogLogsPlugin$Companion$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogLogsPlugin`
class DatadogLogsPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogLogsPlugin> $type;

  @jni$_.internal
  DatadogLogsPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogLogsPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogLogsPlugin$NullableType();
  static const type = $DatadogLogsPlugin$Type();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/datadoghq/flutter/DatadogLogsPlugin$Companion;',
  );

  /// from: `static public final com.datadoghq.flutter.DatadogLogsPlugin$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static DatadogLogsPlugin$Companion get Companion =>
      _id_Companion.get(_class, const $DatadogLogsPlugin$Companion$Type());

  static final _id_LOG_LEVEL = _class.staticFieldId(
    r'LOG_LEVEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_LEVEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_LEVEL =>
      _id_LOG_LEVEL.get(_class, const jni$_.JStringType());

  static final _id_LOG_MESSAGE = _class.staticFieldId(
    r'LOG_MESSAGE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_MESSAGE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_MESSAGE =>
      _id_LOG_MESSAGE.get(_class, const jni$_.JStringType());

  static final _id_LOG_CONTEXT = _class.staticFieldId(
    r'LOG_CONTEXT',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_CONTEXT`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_CONTEXT =>
      _id_LOG_CONTEXT.get(_class, const jni$_.JStringType());

  static final _id_LOG_ERROR_MESSAGE = _class.staticFieldId(
    r'LOG_ERROR_MESSAGE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_ERROR_MESSAGE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_ERROR_MESSAGE =>
      _id_LOG_ERROR_MESSAGE.get(_class, const jni$_.JStringType());

  static final _id_LOG_ERROR_KIND = _class.staticFieldId(
    r'LOG_ERROR_KIND',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_ERROR_KIND`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_ERROR_KIND =>
      _id_LOG_ERROR_KIND.get(_class, const jni$_.JStringType());

  static final _id_LOG_STACK_TRACE = _class.staticFieldId(
    r'LOG_STACK_TRACE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_STACK_TRACE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_STACK_TRACE =>
      _id_LOG_STACK_TRACE.get(_class, const jni$_.JStringType());

  static final _id_LOG_KEY = _class.staticFieldId(
    r'LOG_KEY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_KEY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_KEY =>
      _id_LOG_KEY.get(_class, const jni$_.JStringType());

  static final _id_LOG_TAG = _class.staticFieldId(
    r'LOG_TAG',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_TAG`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_TAG =>
      _id_LOG_TAG.get(_class, const jni$_.JStringType());

  static final _id_LOG_VALUE = _class.staticFieldId(
    r'LOG_VALUE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String LOG_VALUE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get LOG_VALUE =>
      _id_LOG_VALUE.get(_class, const jni$_.JStringType());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogLogsPlugin() {
    return DatadogLogsPlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_attachToEngine = _class.instanceMethodId(
    r'attachToEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _attachToEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void attachToEngine(io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding flutterPluginBinding)`
  void attachToEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _attachToEngine(
      reference.pointer,
      _id_attachToEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_detachFromEngine = _class.instanceMethodId(
    r'detachFromEngine',
    r'()V',
  );

  static final _detachFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final void detachFromEngine()`
  void detachFromEngine() {
    _detachFromEngine(
      reference.pointer,
      _id_detachFromEngine as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_getLogger = _class.instanceMethodId(
    r'getLogger',
    r'(Ljava/lang/String;)Lcom/datadog/android/log/Logger;',
  );

  static final _getLogger =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final com.datadog.android.log.Logger getLogger(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getLogger(jni$_.JString string) {
    final _$string = string.reference;
    return _getLogger(
      reference.pointer,
      _id_getLogger as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_onMethodCall = _class.instanceMethodId(
    r'onMethodCall',
    r'(Lio/flutter/plugin/common/MethodCall;Lio/flutter/plugin/common/MethodChannel$Result;)V',
  );

  static final _onMethodCall =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onMethodCall(io.flutter.plugin.common.MethodCall methodCall, io.flutter.plugin.common.MethodChannel$Result result)`
  void onMethodCall(jni$_.JObject methodCall, jni$_.JObject result) {
    final _$methodCall = methodCall.reference;
    final _$result = result.reference;
    _onMethodCall(
      reference.pointer,
      _id_onMethodCall as jni$_.JMethodIDPtr,
      _$methodCall.pointer,
      _$result.pointer,
    ).check();
  }

  static final _id_setLogsEventMapper = _class.staticMethodId(
    r'setLogsEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;)V',
  );

  static final _setLogsEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void setLogsEventMapper(com.datadoghq.flutter.DatadogLogEventMapper$EventMapper eventMapper)`
  static void setLogsEventMapper(
    DatadogLogEventMapper$EventMapper eventMapper,
  ) {
    final _$eventMapper = eventMapper.reference;
    _setLogsEventMapper(
      _class.reference.pointer,
      _id_setLogsEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }
}

final class $DatadogLogsPlugin$NullableType
    extends jni$_.JObjType<DatadogLogsPlugin?> {
  @jni$_.internal
  const $DatadogLogsPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogLogsPlugin;';

  @jni$_.internal
  @core$_.override
  DatadogLogsPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : DatadogLogsPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogsPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogsPlugin$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogsPlugin$NullableType) &&
        other is $DatadogLogsPlugin$NullableType;
  }
}

final class $DatadogLogsPlugin$Type extends jni$_.JObjType<DatadogLogsPlugin> {
  @jni$_.internal
  const $DatadogLogsPlugin$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogLogsPlugin;';

  @jni$_.internal
  @core$_.override
  DatadogLogsPlugin fromReference(jni$_.JReference reference) =>
      DatadogLogsPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogsPlugin?> get nullableType =>
      const $DatadogLogsPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogsPlugin$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogsPlugin$Type) &&
        other is $DatadogLogsPlugin$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogLogEventMapper$EventMapper`
class DatadogLogEventMapper$EventMapper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogLogEventMapper$EventMapper> $type;

  @jni$_.internal
  DatadogLogEventMapper$EventMapper.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogLogEventMapper$EventMapper',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogLogEventMapper$EventMapper$NullableType();
  static const type = $DatadogLogEventMapper$EventMapper$Type();
  static final _id_mapLogEvent = _class.instanceMethodId(
    r'mapLogEvent',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _mapLogEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.String mapLogEvent(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? mapLogEvent(jni$_.JString string) {
    final _$string = string.reference;
    return _mapLogEvent(
      reference.pointer,
      _id_mapLogEvent as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $DatadogLogEventMapper$EventMapper> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'mapLogEvent(Ljava/lang/String;)Ljava/lang/String;') {
        final $r = _$impls[$p]!.mapLogEvent(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.JObjectType())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $DatadogLogEventMapper$EventMapper $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.datadoghq.flutter.DatadogLogEventMapper$EventMapper',
      $p,
      _$invokePointer,
      [],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory DatadogLogEventMapper$EventMapper.implement(
    $DatadogLogEventMapper$EventMapper $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return DatadogLogEventMapper$EventMapper.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $DatadogLogEventMapper$EventMapper {
  factory $DatadogLogEventMapper$EventMapper({
    required jni$_.JString? Function(jni$_.JString string) mapLogEvent,
  }) = _$DatadogLogEventMapper$EventMapper;

  jni$_.JString? mapLogEvent(jni$_.JString string);
}

final class _$DatadogLogEventMapper$EventMapper
    with $DatadogLogEventMapper$EventMapper {
  _$DatadogLogEventMapper$EventMapper({
    required jni$_.JString? Function(jni$_.JString string) mapLogEvent,
  }) : _mapLogEvent = mapLogEvent;

  final jni$_.JString? Function(jni$_.JString string) _mapLogEvent;

  jni$_.JString? mapLogEvent(jni$_.JString string) {
    return _mapLogEvent(string);
  }
}

final class $DatadogLogEventMapper$EventMapper$NullableType
    extends jni$_.JObjType<DatadogLogEventMapper$EventMapper?> {
  @jni$_.internal
  const $DatadogLogEventMapper$EventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogLogEventMapper$EventMapper? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : DatadogLogEventMapper$EventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogEventMapper$EventMapper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($DatadogLogEventMapper$EventMapper$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($DatadogLogEventMapper$EventMapper$NullableType) &&
        other is $DatadogLogEventMapper$EventMapper$NullableType;
  }
}

final class $DatadogLogEventMapper$EventMapper$Type
    extends jni$_.JObjType<DatadogLogEventMapper$EventMapper> {
  @jni$_.internal
  const $DatadogLogEventMapper$EventMapper$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogLogEventMapper$EventMapper fromReference(jni$_.JReference reference) =>
      DatadogLogEventMapper$EventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogEventMapper$EventMapper?> get nullableType =>
      const $DatadogLogEventMapper$EventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogEventMapper$EventMapper$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogEventMapper$EventMapper$Type) &&
        other is $DatadogLogEventMapper$EventMapper$Type;
  }
}

/// from: `com.datadoghq.flutter.DatadogLogEventMapper`
class DatadogLogEventMapper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DatadogLogEventMapper> $type;

  @jni$_.internal
  DatadogLogEventMapper.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/DatadogLogEventMapper',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DatadogLogEventMapper$NullableType();
  static const type = $DatadogLogEventMapper$Type();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DatadogLogEventMapper() {
    return DatadogLogEventMapper.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_getEventMapper = _class.instanceMethodId(
    r'getEventMapper',
    r'()Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;',
  );

  static final _getEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.DatadogLogEventMapper$EventMapper getEventMapper()`
  /// The returned object must be released after use, by calling the [release] method.
  DatadogLogEventMapper$EventMapper? getEventMapper() {
    return _getEventMapper(
      reference.pointer,
      _id_getEventMapper as jni$_.JMethodIDPtr,
    ).object<DatadogLogEventMapper$EventMapper?>(
      const $DatadogLogEventMapper$EventMapper$NullableType(),
    );
  }

  static final _id_setEventMapper = _class.instanceMethodId(
    r'setEventMapper',
    r'(Lcom/datadoghq/flutter/DatadogLogEventMapper$EventMapper;)V',
  );

  static final _setEventMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setEventMapper(com.datadoghq.flutter.DatadogLogEventMapper$EventMapper eventMapper)`
  void setEventMapper(DatadogLogEventMapper$EventMapper? eventMapper) {
    final _$eventMapper = eventMapper?.reference ?? jni$_.jNullReference;
    _setEventMapper(
      reference.pointer,
      _id_setEventMapper as jni$_.JMethodIDPtr,
      _$eventMapper.pointer,
    ).check();
  }

  static final _id_attachMapper = _class.instanceMethodId(
    r'attachMapper',
    r'(Lcom/datadog/android/log/LogsConfiguration$Builder;)Lcom/datadog/android/log/LogsConfiguration$Builder;',
  );

  static final _attachMapper =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final com.datadog.android.log.LogsConfiguration$Builder attachMapper(com.datadog.android.log.LogsConfiguration$Builder builder)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject attachMapper(jni$_.JObject builder) {
    final _$builder = builder.reference;
    return _attachMapper(
      reference.pointer,
      _id_attachMapper as jni$_.JMethodIDPtr,
      _$builder.pointer,
    ).object<jni$_.JObject>(const jni$_.JObjectType());
  }
}

final class $DatadogLogEventMapper$NullableType
    extends jni$_.JObjType<DatadogLogEventMapper?> {
  @jni$_.internal
  const $DatadogLogEventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogLogEventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogLogEventMapper? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : DatadogLogEventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogEventMapper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogEventMapper$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogEventMapper$NullableType) &&
        other is $DatadogLogEventMapper$NullableType;
  }
}

final class $DatadogLogEventMapper$Type
    extends jni$_.JObjType<DatadogLogEventMapper> {
  @jni$_.internal
  const $DatadogLogEventMapper$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadoghq/flutter/DatadogLogEventMapper;';

  @jni$_.internal
  @core$_.override
  DatadogLogEventMapper fromReference(jni$_.JReference reference) =>
      DatadogLogEventMapper.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DatadogLogEventMapper?> get nullableType =>
      const $DatadogLogEventMapper$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DatadogLogEventMapper$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DatadogLogEventMapper$Type) &&
        other is $DatadogLogEventMapper$Type;
  }
}
