include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
