include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: ["**/src/generated/**"]
  language:
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    unawaited_futures: true
