name: datadog_flutter_plugin_platform_interface
description: Platform interface for the datadog_flutter_plugin package.
version: 1.0.0
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.12.0
  meta: ^1.7.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"
  json_serializable: ^6.14.1
  build_runner: ^2.15.1
