name: datadog_flutter_plugin
description: Flutter bindings and tools for utilizing Datadog Mobile SDks
version: 4.0.0
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  uuid: ^4.0.0
  datadog_flutter_plugin_platform_interface: ^1.0.0
  datadog_flutter_plugin_android: ^1.0.0
  datadog_flutter_plugin_ios: ^1.0.0
  datadog_flutter_plugin_web: ^1.0.0
  datadog_flutter_plugin_desktop: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"
  mocktail: ^1.0.4
  datadog_common_test:
    path: ../../datadog_common_test
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: datadog_flutter_plugin_android
      ios:
        default_package: datadog_flutter_plugin_ios
      macos:
        default_package: datadog_flutter_plugin_ios
      web:
        default_package: datadog_flutter_plugin_web
      windows:
        default_package: datadog_flutter_plugin_desktop
      linux:
        default_package: datadog_flutter_plugin_desktop
