name: datadog_session_replay_example
description: "Demonstrates how to use the datadog_session_replay plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  datadog_flutter_plugin: ^3.0.0
  datadog_session_replay:
    path: ../
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  flutter_test_goldens: ^0.0.7
  datadog_common_test:
    path: ../../datadog_common_test

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/dd_logo_v_rgb.png
