name: datadog_session_replay_example
description: "Serves as a test bed for Dataog Session Replay"
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  datadog_flutter_plugin: ^2.1.0
  datadog_session_replay:
    path: ../
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env