// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$Configuration`
class FlutterSessionReplayBridge$Configuration extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<FlutterSessionReplayBridge$Configuration> $type;

  @jni$_.internal
  FlutterSessionReplayBridge$Configuration.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration');

  /// The type which includes information such as the signature of this class.
  static const nullableType =
      $FlutterSessionReplayBridge$Configuration$NullableType();
  static const type = $FlutterSessionReplayBridge$Configuration$Type();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void <init>(java.lang.String string, com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$Configuration(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener contextListener,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener = contextListener.reference;
    return FlutterSessionReplayBridge$Configuration.fromReference(_new$(
            _class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$contextListener.pointer)
        .reference);
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `synthetic public void <init>(java.lang.String string, com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$Configuration.new$1(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener? contextListener,
    int i,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener =
        contextListener?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return FlutterSessionReplayBridge$Configuration.fromReference(_new$1(
            _class.reference.pointer,
            _id_new$1 as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$contextListener.pointer,
            i,
            _$defaultConstructorMarker.pointer)
        .reference);
  }

  static final _id_getCustomEndpointUrl = _class.instanceMethodId(
    r'getCustomEndpointUrl',
    r'()Ljava/lang/String;',
  );

  static final _getCustomEndpointUrl = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String getCustomEndpointUrl()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getCustomEndpointUrl() {
    return _getCustomEndpointUrl(
            reference.pointer, _id_getCustomEndpointUrl as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_getOnContextChanged = _class.instanceMethodId(
    r'getOnContextChanged',
    r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
  );

  static final _getOnContextChanged = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener getOnContextChanged()`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener getOnContextChanged() {
    return _getOnContextChanged(
            reference.pointer, _id_getOnContextChanged as jni$_.JMethodIDPtr)
        .object<FlutterSessionReplayBridge$ContextListener>(
            const $FlutterSessionReplayBridge$ContextListener$Type());
  }

  static final _id_component1 = _class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/String;',
  );

  static final _component1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String component1()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component1() {
    return _component1(reference.pointer, _id_component1 as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_component2 = _class.instanceMethodId(
    r'component2',
    r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
  );

  static final _component2 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener component2()`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener component2() {
    return _component2(reference.pointer, _id_component2 as jni$_.JMethodIDPtr)
        .object<FlutterSessionReplayBridge$ContextListener>(
            const $FlutterSessionReplayBridge$ContextListener$Type());
  }

  static final _id_copy = _class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;',
  );

  static final _copy = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$Configuration copy(java.lang.String string, com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener)`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$Configuration copy(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener contextListener,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener = contextListener.reference;
    return _copy(reference.pointer, _id_copy as jni$_.JMethodIDPtr,
            _$string.pointer, _$contextListener.pointer)
        .object<FlutterSessionReplayBridge$Configuration>(
            const $FlutterSessionReplayBridge$Configuration$Type());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(reference.pointer, _id_toString$1 as jni$_.JMethodIDPtr)
        .object<jni$_.JString>(const jni$_.JStringType());
  }

  static final _id_hashCode$1 = _class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1 as jni$_.JMethodIDPtr)
        .integer;
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(
    jni$_.JObject? object,
  ) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(reference.pointer, _id_equals as jni$_.JMethodIDPtr,
            _$object.pointer)
        .boolean;
  }
}

final class $FlutterSessionReplayBridge$Configuration$NullableType
    extends jni$_.JObjType<FlutterSessionReplayBridge$Configuration?> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$Configuration$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$Configuration? fromReference(
          jni$_.JReference reference) =>
      reference.isNull
          ? null
          : FlutterSessionReplayBridge$Configuration.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$Configuration?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($FlutterSessionReplayBridge$Configuration$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($FlutterSessionReplayBridge$Configuration$NullableType) &&
        other is $FlutterSessionReplayBridge$Configuration$NullableType;
  }
}

final class $FlutterSessionReplayBridge$Configuration$Type
    extends jni$_.JObjType<FlutterSessionReplayBridge$Configuration> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$Configuration$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$Configuration fromReference(
          jni$_.JReference reference) =>
      FlutterSessionReplayBridge$Configuration.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$Configuration?> get nullableType =>
      const $FlutterSessionReplayBridge$Configuration$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FlutterSessionReplayBridge$Configuration$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($FlutterSessionReplayBridge$Configuration$Type) &&
        other is $FlutterSessionReplayBridge$Configuration$Type;
  }
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener`
class FlutterSessionReplayBridge$ContextListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<FlutterSessionReplayBridge$ContextListener> $type;

  @jni$_.internal
  FlutterSessionReplayBridge$ContextListener.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener');

  /// The type which includes information such as the signature of this class.
  static const nullableType =
      $FlutterSessionReplayBridge$ContextListener$NullableType();
  static const type = $FlutterSessionReplayBridge$ContextListener$Type();
  static final _id_onContextChanged = _class.instanceMethodId(
    r'onContextChanged',
    r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V',
  );

  static final _onContextChanged = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onContextChanged(com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$RumContext rumContext)`
  void onContextChanged(
    FlutterSessionReplayBridge$RumContext rumContext,
  ) {
    final _$rumContext = rumContext.reference;
    _onContextChanged(reference.pointer,
            _id_onContextChanged as jni$_.JMethodIDPtr, _$rumContext.pointer)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $FlutterSessionReplayBridge$ContextListener>
      _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d ==
          r'onContextChanged(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V') {
        _$impls[$p]!.onContextChanged(
          $a![0]!.as(const $FlutterSessionReplayBridge$RumContext$Type(),
              releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $FlutterSessionReplayBridge$ContextListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener',
      $p,
      _$invokePointer,
      [
        if ($impl.onContextChanged$async)
          r'onContextChanged(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory FlutterSessionReplayBridge$ContextListener.implement(
    $FlutterSessionReplayBridge$ContextListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return FlutterSessionReplayBridge$ContextListener.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $FlutterSessionReplayBridge$ContextListener {
  factory $FlutterSessionReplayBridge$ContextListener({
    required void Function(FlutterSessionReplayBridge$RumContext rumContext)
        onContextChanged,
    bool onContextChanged$async,
  }) = _$FlutterSessionReplayBridge$ContextListener;

  void onContextChanged(FlutterSessionReplayBridge$RumContext rumContext);
  bool get onContextChanged$async => false;
}

final class _$FlutterSessionReplayBridge$ContextListener
    with $FlutterSessionReplayBridge$ContextListener {
  _$FlutterSessionReplayBridge$ContextListener({
    required void Function(FlutterSessionReplayBridge$RumContext rumContext)
        onContextChanged,
    this.onContextChanged$async = false,
  }) : _onContextChanged = onContextChanged;

  final void Function(FlutterSessionReplayBridge$RumContext rumContext)
      _onContextChanged;
  final bool onContextChanged$async;

  void onContextChanged(FlutterSessionReplayBridge$RumContext rumContext) {
    return _onContextChanged(rumContext);
  }
}

final class $FlutterSessionReplayBridge$ContextListener$NullableType
    extends jni$_.JObjType<FlutterSessionReplayBridge$ContextListener?> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$ContextListener$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$ContextListener? fromReference(
          jni$_.JReference reference) =>
      reference.isNull
          ? null
          : FlutterSessionReplayBridge$ContextListener.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$ContextListener?>
      get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($FlutterSessionReplayBridge$ContextListener$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($FlutterSessionReplayBridge$ContextListener$NullableType) &&
        other is $FlutterSessionReplayBridge$ContextListener$NullableType;
  }
}

final class $FlutterSessionReplayBridge$ContextListener$Type
    extends jni$_.JObjType<FlutterSessionReplayBridge$ContextListener> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$ContextListener$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$ContextListener fromReference(
          jni$_.JReference reference) =>
      FlutterSessionReplayBridge$ContextListener.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$ContextListener?>
      get nullableType =>
          const $FlutterSessionReplayBridge$ContextListener$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($FlutterSessionReplayBridge$ContextListener$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($FlutterSessionReplayBridge$ContextListener$Type) &&
        other is $FlutterSessionReplayBridge$ContextListener$Type;
  }
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$RumContext`
class FlutterSessionReplayBridge$RumContext extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<FlutterSessionReplayBridge$RumContext> $type;

  @jni$_.internal
  FlutterSessionReplayBridge$RumContext.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext');

  /// The type which includes information such as the signature of this class.
  static const nullableType =
      $FlutterSessionReplayBridge$RumContext$NullableType();
  static const type = $FlutterSessionReplayBridge$RumContext$Type();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Long;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.Long long)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$RumContext(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JLong? long,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$long = long?.reference ?? jni$_.jNullReference;
    return FlutterSessionReplayBridge$RumContext.fromReference(_new$(
            _class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$long.pointer)
        .reference);
  }

  static final _id_getApplicationId = _class.instanceMethodId(
    r'getApplicationId',
    r'()Ljava/lang/String;',
  );

  static final _getApplicationId = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String getApplicationId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getApplicationId() {
    return _getApplicationId(
            reference.pointer, _id_getApplicationId as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_getSessionId = _class.instanceMethodId(
    r'getSessionId',
    r'()Ljava/lang/String;',
  );

  static final _getSessionId = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String getSessionId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getSessionId() {
    return _getSessionId(
            reference.pointer, _id_getSessionId as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_getViewId = _class.instanceMethodId(
    r'getViewId',
    r'()Ljava/lang/String;',
  );

  static final _getViewId = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String getViewId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getViewId() {
    return _getViewId(reference.pointer, _id_getViewId as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_getViewServerTimeOffset = _class.instanceMethodId(
    r'getViewServerTimeOffset',
    r'()Ljava/lang/Long;',
  );

  static final _getViewServerTimeOffset = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.Long getViewServerTimeOffset()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLong? getViewServerTimeOffset() {
    return _getViewServerTimeOffset(reference.pointer,
            _id_getViewServerTimeOffset as jni$_.JMethodIDPtr)
        .object<jni$_.JLong?>(const jni$_.JLongNullableType());
  }

  static final _id_new$1 = _class.constructorId(
    r'(Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature$RumContext;)V',
  );

  static final _new$1 = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void <init>(com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature$RumContext rumContext)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$RumContext.new$1(
    jni$_.JObject rumContext,
  ) {
    final _$rumContext = rumContext.reference;
    return FlutterSessionReplayBridge$RumContext.fromReference(_new$1(
            _class.reference.pointer,
            _id_new$1 as jni$_.JMethodIDPtr,
            _$rumContext.pointer)
        .reference);
  }

  static final _id_component1 = _class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/String;',
  );

  static final _component1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String component1()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component1() {
    return _component1(reference.pointer, _id_component1 as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_component2 = _class.instanceMethodId(
    r'component2',
    r'()Ljava/lang/String;',
  );

  static final _component2 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String component2()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component2() {
    return _component2(reference.pointer, _id_component2 as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_component3 = _class.instanceMethodId(
    r'component3',
    r'()Ljava/lang/String;',
  );

  static final _component3 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.String component3()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component3() {
    return _component3(reference.pointer, _id_component3 as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_component4 = _class.instanceMethodId(
    r'component4',
    r'()Ljava/lang/Long;',
  );

  static final _component4 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.lang.Long component4()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLong? component4() {
    return _component4(reference.pointer, _id_component4 as jni$_.JMethodIDPtr)
        .object<jni$_.JLong?>(const jni$_.JLongNullableType());
  }

  static final _id_copy = _class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Long;)Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;',
  );

  static final _copy = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$RumContext copy(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.Long long)`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$RumContext copy(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JLong? long,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$long = long?.reference ?? jni$_.jNullReference;
    return _copy(
            reference.pointer,
            _id_copy as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$long.pointer)
        .object<FlutterSessionReplayBridge$RumContext>(
            const $FlutterSessionReplayBridge$RumContext$Type());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(reference.pointer, _id_toString$1 as jni$_.JMethodIDPtr)
        .object<jni$_.JString>(const jni$_.JStringType());
  }

  static final _id_hashCode$1 = _class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1 as jni$_.JMethodIDPtr)
        .integer;
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(
    jni$_.JObject? object,
  ) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(reference.pointer, _id_equals as jni$_.JMethodIDPtr,
            _$object.pointer)
        .boolean;
  }
}

final class $FlutterSessionReplayBridge$RumContext$NullableType
    extends jni$_.JObjType<FlutterSessionReplayBridge$RumContext?> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$RumContext$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$RumContext? fromReference(
          jni$_.JReference reference) =>
      reference.isNull
          ? null
          : FlutterSessionReplayBridge$RumContext.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$RumContext?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($FlutterSessionReplayBridge$RumContext$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($FlutterSessionReplayBridge$RumContext$NullableType) &&
        other is $FlutterSessionReplayBridge$RumContext$NullableType;
  }
}

final class $FlutterSessionReplayBridge$RumContext$Type
    extends jni$_.JObjType<FlutterSessionReplayBridge$RumContext> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$RumContext$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge$RumContext fromReference(
          jni$_.JReference reference) =>
      FlutterSessionReplayBridge$RumContext.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge$RumContext?> get nullableType =>
      const $FlutterSessionReplayBridge$RumContext$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FlutterSessionReplayBridge$RumContext$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FlutterSessionReplayBridge$RumContext$Type) &&
        other is $FlutterSessionReplayBridge$RumContext$Type;
  }
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge`
class FlutterSessionReplayBridge extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<FlutterSessionReplayBridge> $type;

  @jni$_.internal
  FlutterSessionReplayBridge.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $FlutterSessionReplayBridge$NullableType();
  static const type = $FlutterSessionReplayBridge$Type();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge;',
  );

  /// from: `static public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static FlutterSessionReplayBridge get INSTANCE =>
      _id_INSTANCE.get(_class, const $FlutterSessionReplayBridge$Type());

  static final _id_getContextListener = _class.instanceMethodId(
    r'getContextListener',
    r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
  );

  static final _getContextListener = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener getContextListener()`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener? getContextListener() {
    return _getContextListener(
            reference.pointer, _id_getContextListener as jni$_.JMethodIDPtr)
        .object<FlutterSessionReplayBridge$ContextListener?>(
            const $FlutterSessionReplayBridge$ContextListener$NullableType());
  }

  static final _id_setContextListener = _class.instanceMethodId(
    r'setContextListener',
    r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)V',
  );

  static final _setContextListener = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void setContextListener(com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener)`
  void setContextListener(
    FlutterSessionReplayBridge$ContextListener? contextListener,
  ) {
    final _$contextListener =
        contextListener?.reference ?? jni$_.jNullReference;
    _setContextListener(
            reference.pointer,
            _id_setContextListener as jni$_.JMethodIDPtr,
            _$contextListener.pointer)
        .check();
  }

  static final _id_getFeature = _class.instanceMethodId(
    r'getFeature',
    r'()Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;',
  );

  static final _getFeature = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature getFeature()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getFeature() {
    return _getFeature(reference.pointer, _id_getFeature as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_setFeature = _class.instanceMethodId(
    r'setFeature',
    r'(Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;)V',
  );

  static final _setFeature = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void setFeature(com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature defaultFlutterSessionReplayFeature)`
  void setFeature(
    jni$_.JObject? defaultFlutterSessionReplayFeature,
  ) {
    final _$defaultFlutterSessionReplayFeature =
        defaultFlutterSessionReplayFeature?.reference ?? jni$_.jNullReference;
    _setFeature(reference.pointer, _id_setFeature as jni$_.JMethodIDPtr,
            _$defaultFlutterSessionReplayFeature.pointer)
        .check();
  }

  static final _id_enable = _class.instanceMethodId(
    r'enable',
    r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;Lcom/datadog/android/api/feature/FeatureSdkCore;)Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;',
  );

  static final _enable = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature enable(com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$Configuration configuration, com.datadog.android.api.feature.FeatureSdkCore featureSdkCore)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject enable(
    FlutterSessionReplayBridge$Configuration configuration,
    jni$_.JObject? featureSdkCore,
  ) {
    final _$configuration = configuration.reference;
    final _$featureSdkCore = featureSdkCore?.reference ?? jni$_.jNullReference;
    return _enable(reference.pointer, _id_enable as jni$_.JMethodIDPtr,
            _$configuration.pointer, _$featureSdkCore.pointer)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_setHasReplay = _class.instanceMethodId(
    r'setHasReplay',
    r'(Ljava/lang/String;Z)V',
  );

  static final _setHasReplay = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, int)>();

  /// from: `public final void setHasReplay(java.lang.String string, boolean z)`
  void setHasReplay(
    jni$_.JString string,
    bool z,
  ) {
    final _$string = string.reference;
    _setHasReplay(reference.pointer, _id_setHasReplay as jni$_.JMethodIDPtr,
            _$string.pointer, z ? 1 : 0)
        .check();
  }

  static final _id_setRecordCount = _class.instanceMethodId(
    r'setRecordCount',
    r'(Ljava/lang/String;I)V',
  );

  static final _setRecordCount = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, int)>();

  /// from: `public final void setRecordCount(java.lang.String string, int i)`
  void setRecordCount(
    jni$_.JString string,
    int i,
  ) {
    final _$string = string.reference;
    _setRecordCount(reference.pointer, _id_setRecordCount as jni$_.JMethodIDPtr,
            _$string.pointer, i)
        .check();
  }

  static final _id_writeSegment = _class.instanceMethodId(
    r'writeSegment',
    r'(Ljava/lang/String;)V',
  );

  static final _writeSegment = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void writeSegment(java.lang.String string)`
  void writeSegment(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _writeSegment(reference.pointer, _id_writeSegment as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  static final _id_telemetryDebug = _class.instanceMethodId(
    r'telemetryDebug',
    r'(Ljava/lang/String;)V',
  );

  static final _telemetryDebug = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void telemetryDebug(java.lang.String string)`
  void telemetryDebug(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _telemetryDebug(reference.pointer, _id_telemetryDebug as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  static final _id_telemetryError = _class.instanceMethodId(
    r'telemetryError',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _telemetryError = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void telemetryError(java.lang.String string, java.lang.String string1, java.lang.String string2)`
  void telemetryError(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    _telemetryError(reference.pointer, _id_telemetryError as jni$_.JMethodIDPtr,
            _$string.pointer, _$string1.pointer, _$string2.pointer)
        .check();
  }

  static final _id_saveImageForProcessing = _class.instanceMethodId(
    r'saveImageForProcessing',
    r'(ILjava/nio/ByteBuffer;II)V',
  );

  static final _saveImageForProcessing = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>, int, int)>();

  /// from: `public final void saveImageForProcessing(int i, java.nio.ByteBuffer byteBuffer, int i1, int i2)`
  void saveImageForProcessing(
    int i,
    jni$_.JByteBuffer byteBuffer,
    int i1,
    int i2,
  ) {
    final _$byteBuffer = byteBuffer.reference;
    _saveImageForProcessing(
            reference.pointer,
            _id_saveImageForProcessing as jni$_.JMethodIDPtr,
            i,
            _$byteBuffer.pointer,
            i1,
            i2)
        .check();
  }

  static final _id_resourceIdForKey = _class.instanceMethodId(
    r'resourceIdForKey',
    r'(I)Ljava/lang/String;',
  );

  static final _resourceIdForKey = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public final java.lang.String resourceIdForKey(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? resourceIdForKey(
    int i,
  ) {
    return _resourceIdForKey(
            reference.pointer, _id_resourceIdForKey as jni$_.JMethodIDPtr, i)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }
}

final class $FlutterSessionReplayBridge$NullableType
    extends jni$_.JObjType<FlutterSessionReplayBridge?> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : FlutterSessionReplayBridge.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FlutterSessionReplayBridge$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FlutterSessionReplayBridge$NullableType) &&
        other is $FlutterSessionReplayBridge$NullableType;
  }
}

final class $FlutterSessionReplayBridge$Type
    extends jni$_.JObjType<FlutterSessionReplayBridge> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge;';

  @jni$_.internal
  @core$_.override
  FlutterSessionReplayBridge fromReference(jni$_.JReference reference) =>
      FlutterSessionReplayBridge.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<FlutterSessionReplayBridge?> get nullableType =>
      const $FlutterSessionReplayBridge$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FlutterSessionReplayBridge$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FlutterSessionReplayBridge$Type) &&
        other is $FlutterSessionReplayBridge$Type;
  }
}
