// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$Configuration`
extension type FlutterSessionReplayBridge$Configuration._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FlutterSessionReplayBridge$Configuration> type =
      $FlutterSessionReplayBridge$Configuration$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string, com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$Configuration(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener contextListener,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener = contextListener.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$contextListener.pointer,
    ).object<FlutterSessionReplayBridge$Configuration>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(java.lang.String string, com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$Configuration.new$1(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener? contextListener,
    core$_.int i,
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener =
        contextListener?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$string.pointer,
      _$contextListener.pointer,
      i,
      _$defaultConstructorMarker.pointer,
    ).object<FlutterSessionReplayBridge$Configuration>();
  }
}

extension FlutterSessionReplayBridge$Configuration$$Methods
    on FlutterSessionReplayBridge$Configuration {
  static final _id_get$customEndpointUrl =
      FlutterSessionReplayBridge$Configuration._class.instanceMethodId(
        r'getCustomEndpointUrl',
        r'()Ljava/lang/String;',
      );

  static final _get$customEndpointUrl =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getCustomEndpointUrl()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get customEndpointUrl {
    final _$$selfRef = reference;
    return _get$customEndpointUrl(
      _$$selfRef.pointer,
      _id_get$customEndpointUrl.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$onContextChanged =
      FlutterSessionReplayBridge$Configuration._class.instanceMethodId(
        r'getOnContextChanged',
        r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
      );

  static final _get$onContextChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener getOnContextChanged()`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener get onContextChanged {
    final _$$selfRef = reference;
    return _get$onContextChanged(
      _$$selfRef.pointer,
      _id_get$onContextChanged.pointer,
    ).object<FlutterSessionReplayBridge$ContextListener>();
  }

  static final _id_component1 = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(r'component1', r'()Ljava/lang/String;');

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component1() {
    final _$$selfRef = reference;
    return _component1(
      _$$selfRef.pointer,
      _id_component1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_component2 = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(
        r'component2',
        r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
      );

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.ContextListener`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener component2() {
    final _$$selfRef = reference;
    return _component2(
      _$$selfRef.pointer,
      _id_component2.pointer,
    ).object<FlutterSessionReplayBridge$ContextListener>();
  }

  static final _id_copy = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(
        r'copy',
        r'(Ljava/lang/String;Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;',
      );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(customEndpointUrl: kotlin.String?, onContextChanged: com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.ContextListener): com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.Configuration`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$Configuration copy(
    jni$_.JString? string,
    FlutterSessionReplayBridge$ContextListener contextListener,
  ) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$contextListener = contextListener.reference;
    return _copy(
      _$$selfRef.pointer,
      _id_copy.pointer,
      _$string.pointer,
      _$contextListener.pointer,
    ).object<FlutterSessionReplayBridge$Configuration>();
  }

  static final _id_toString$1 = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(r'toString', r'()Ljava/lang/String;');

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_hashCode$1 = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = FlutterSessionReplayBridge$Configuration._class
      .instanceMethodId(r'equals', r'(Ljava/lang/Object;)Z');

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(jni$_.JObject? object) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $FlutterSessionReplayBridge$Configuration$Type$
    extends jni$_.JType<FlutterSessionReplayBridge$Configuration> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$Configuration$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;';
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener`
extension type FlutterSessionReplayBridge$ContextListener._(
  jni$_.JObject _$this
)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FlutterSessionReplayBridge$ContextListener> type =
      $FlutterSessionReplayBridge$ContextListener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<
    core$_.int,
    $FlutterSessionReplayBridge$ContextListener
  >
  _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d ==
          r'onContextChanged(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V') {
        _$impls[$p]!.onContextChanged(
          ($a![0] as FlutterSessionReplayBridge$RumContext),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $FlutterSessionReplayBridge$ContextListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener',
      $p,
      _$invokePointer,
      [
        if ($impl.onContextChanged$async)
          r'onContextChanged(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory FlutterSessionReplayBridge$ContextListener.implement(
    $FlutterSessionReplayBridge$ContextListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<FlutterSessionReplayBridge$ContextListener>();
  }
}

extension FlutterSessionReplayBridge$ContextListener$$Methods
    on FlutterSessionReplayBridge$ContextListener {
  static final _id_onContextChanged = FlutterSessionReplayBridge$ContextListener
      ._class
      .instanceMethodId(
        r'onContextChanged',
        r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;)V',
      );

  static final _onContextChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onContextChanged(context: com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.RumContext): kotlin.Unit`
  void onContextChanged(FlutterSessionReplayBridge$RumContext rumContext) {
    final _$$selfRef = reference;
    final _$rumContext = rumContext.reference;
    _onContextChanged(
      _$$selfRef.pointer,
      _id_onContextChanged.pointer,
      _$rumContext.pointer,
    ).check();
  }
}

abstract base mixin class $FlutterSessionReplayBridge$ContextListener {
  factory $FlutterSessionReplayBridge$ContextListener({
    required void Function(FlutterSessionReplayBridge$RumContext rumContext)
    onContextChanged,
    core$_.bool onContextChanged$async,
  }) = _$FlutterSessionReplayBridge$ContextListener;

  void onContextChanged(FlutterSessionReplayBridge$RumContext rumContext);
  core$_.bool get onContextChanged$async => false;
}

final class _$FlutterSessionReplayBridge$ContextListener
    with $FlutterSessionReplayBridge$ContextListener {
  _$FlutterSessionReplayBridge$ContextListener({
    required void Function(FlutterSessionReplayBridge$RumContext rumContext)
    onContextChanged,
    this.onContextChanged$async = false,
  }) : _onContextChanged = onContextChanged;

  final void Function(FlutterSessionReplayBridge$RumContext rumContext)
  _onContextChanged;
  final core$_.bool onContextChanged$async;

  void onContextChanged(FlutterSessionReplayBridge$RumContext rumContext) {
    return _onContextChanged(rumContext);
  }
}

final class $FlutterSessionReplayBridge$ContextListener$Type$
    extends jni$_.JType<FlutterSessionReplayBridge$ContextListener> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$ContextListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;';
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$RumContext`
extension type FlutterSessionReplayBridge$RumContext._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FlutterSessionReplayBridge$RumContext> type =
      $FlutterSessionReplayBridge$RumContext$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Long;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.Long long)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$RumContext(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JLong? long,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$long = long?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$long.pointer,
    ).object<FlutterSessionReplayBridge$RumContext>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature$RumContext;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature$RumContext rumContext)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterSessionReplayBridge$RumContext.new$1(
    DefaultFlutterSessionReplayFeature$$RumContext rumContext,
  ) {
    final _$$classRef = _class.reference;
    final _$rumContext = rumContext.reference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$rumContext.pointer,
    ).object<FlutterSessionReplayBridge$RumContext>();
  }
}

extension FlutterSessionReplayBridge$RumContext$$Methods
    on FlutterSessionReplayBridge$RumContext {
  static final _id_get$applicationId = FlutterSessionReplayBridge$RumContext
      ._class
      .instanceMethodId(r'getApplicationId', r'()Ljava/lang/String;');

  static final _get$applicationId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getApplicationId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get applicationId {
    final _$$selfRef = reference;
    return _get$applicationId(
      _$$selfRef.pointer,
      _id_get$applicationId.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$sessionId = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'getSessionId', r'()Ljava/lang/String;');

  static final _get$sessionId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getSessionId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get sessionId {
    final _$$selfRef = reference;
    return _get$sessionId(
      _$$selfRef.pointer,
      _id_get$sessionId.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$viewId = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'getViewId', r'()Ljava/lang/String;');

  static final _get$viewId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getViewId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get viewId {
    final _$$selfRef = reference;
    return _get$viewId(
      _$$selfRef.pointer,
      _id_get$viewId.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$viewServerTimeOffset =
      FlutterSessionReplayBridge$RumContext._class.instanceMethodId(
        r'getViewServerTimeOffset',
        r'()Ljava/lang/Long;',
      );

  static final _get$viewServerTimeOffset =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Long getViewServerTimeOffset()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLong? get viewServerTimeOffset {
    final _$$selfRef = reference;
    return _get$viewServerTimeOffset(
      _$$selfRef.pointer,
      _id_get$viewServerTimeOffset.pointer,
    ).object<jni$_.JLong?>();
  }

  static final _id_component1 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'component1', r'()Ljava/lang/String;');

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component1() {
    final _$$selfRef = reference;
    return _component1(
      _$$selfRef.pointer,
      _id_component1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_component2 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'component2', r'()Ljava/lang/String;');

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component2() {
    final _$$selfRef = reference;
    return _component2(
      _$$selfRef.pointer,
      _id_component2.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_component3 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'component3', r'()Ljava/lang/String;');

  static final _component3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component3(): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? component3() {
    final _$$selfRef = reference;
    return _component3(
      _$$selfRef.pointer,
      _id_component3.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_component4 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'component4', r'()Ljava/lang/Long;');

  static final _component4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component4(): kotlin.Long?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLong? component4() {
    final _$$selfRef = reference;
    return _component4(
      _$$selfRef.pointer,
      _id_component4.pointer,
    ).object<jni$_.JLong?>();
  }

  static final _id_copy = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(
        r'copy',
        r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Long;)Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;',
      );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(applicationId: kotlin.String?, sessionId: kotlin.String?, viewId: kotlin.String?, viewServerTimeOffset: kotlin.Long?): com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.RumContext`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$RumContext copy(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JLong? long,
  ) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$long = long?.reference ?? jni$_.jNullReference;
    return _copy(
      _$$selfRef.pointer,
      _id_copy.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$long.pointer,
    ).object<FlutterSessionReplayBridge$RumContext>();
  }

  static final _id_toString$1 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'toString', r'()Ljava/lang/String;');

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_hashCode$1 = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = FlutterSessionReplayBridge$RumContext._class
      .instanceMethodId(r'equals', r'(Ljava/lang/Object;)Z');

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(jni$_.JObject? object) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $FlutterSessionReplayBridge$RumContext$Type$
    extends jni$_.JType<FlutterSessionReplayBridge$RumContext> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$RumContext$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$RumContext;';
}

/// from: `com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge`
extension type FlutterSessionReplayBridge._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FlutterSessionReplayBridge> type =
      $FlutterSessionReplayBridge$Type$();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge;',
  );

  /// from: `static public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static FlutterSessionReplayBridge get INSTANCE =>
      _id_INSTANCE.get(_class, FlutterSessionReplayBridge.type)
          as FlutterSessionReplayBridge;
}

extension FlutterSessionReplayBridge$$Methods on FlutterSessionReplayBridge {
  static final _id_get$contextListener = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'getContextListener',
        r'()Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;',
      );

  static final _get$contextListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener getContextListener()`
  /// The returned object must be released after use, by calling the [release] method.
  FlutterSessionReplayBridge$ContextListener? get contextListener {
    final _$$selfRef = reference;
    return _get$contextListener(
      _$$selfRef.pointer,
      _id_get$contextListener.pointer,
    ).object<FlutterSessionReplayBridge$ContextListener?>();
  }

  static final _id_set$contextListener = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'setContextListener',
        r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$ContextListener;)V',
      );

  static final _set$contextListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setContextListener(com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge$ContextListener contextListener)`
  set contextListener(
    FlutterSessionReplayBridge$ContextListener? contextListener,
  ) {
    final _$$selfRef = reference;
    final _$contextListener =
        contextListener?.reference ?? jni$_.jNullReference;
    _set$contextListener(
      _$$selfRef.pointer,
      _id_set$contextListener.pointer,
      _$contextListener.pointer,
    ).check();
  }

  static final _id_get$feature = FlutterSessionReplayBridge._class.instanceMethodId(
    r'getFeature',
    r'()Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;',
  );

  static final _get$feature =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature getFeature()`
  /// The returned object must be released after use, by calling the [release] method.
  DefaultFlutterSessionReplayFeature? get feature {
    final _$$selfRef = reference;
    return _get$feature(
      _$$selfRef.pointer,
      _id_get$feature.pointer,
    ).object<DefaultFlutterSessionReplayFeature?>();
  }

  static final _id_set$feature = FlutterSessionReplayBridge._class.instanceMethodId(
    r'setFeature',
    r'(Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;)V',
  );

  static final _set$feature =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setFeature(com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature defaultFlutterSessionReplayFeature)`
  set feature(
    DefaultFlutterSessionReplayFeature? defaultFlutterSessionReplayFeature,
  ) {
    final _$$selfRef = reference;
    final _$defaultFlutterSessionReplayFeature =
        defaultFlutterSessionReplayFeature?.reference ?? jni$_.jNullReference;
    _set$feature(
      _$$selfRef.pointer,
      _id_set$feature.pointer,
      _$defaultFlutterSessionReplayFeature.pointer,
    ).check();
  }

  static final _id_claimOwnership = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'claimOwnership',
        r'(Lio/flutter/plugin/common/BinaryMessenger;)V',
      );

  static final _claimOwnership =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun claimOwnership(messenger: io.flutter.plugin.common.BinaryMessenger): kotlin.Unit`
  void claimOwnership(BinaryMessenger binaryMessenger) {
    final _$$selfRef = reference;
    final _$binaryMessenger = binaryMessenger.reference;
    _claimOwnership(
      _$$selfRef.pointer,
      _id_claimOwnership.pointer,
      _$binaryMessenger.pointer,
    ).check();
  }

  static final _id_enable = FlutterSessionReplayBridge._class.instanceMethodId(
    r'enable',
    r'(Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge$Configuration;Lcom/datadog/android/api/feature/FeatureSdkCore;)Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;',
  );

  static final _enable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun enable(configuration: com.datadoghq.flutter.sessionreplay.FlutterSessionReplayBridge.Configuration, core: com.datadog.android.api.feature.FeatureSdkCore?): com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature`
  /// The returned object must be released after use, by calling the [release] method.
  DefaultFlutterSessionReplayFeature enable(
    FlutterSessionReplayBridge$Configuration configuration,
    FeatureSdkCore? featureSdkCore,
  ) {
    final _$$selfRef = reference;
    final _$configuration = configuration.reference;
    final _$featureSdkCore = featureSdkCore?.reference ?? jni$_.jNullReference;
    return _enable(
      _$$selfRef.pointer,
      _id_enable.pointer,
      _$configuration.pointer,
      _$featureSdkCore.pointer,
    ).object<DefaultFlutterSessionReplayFeature>();
  }

  static final _id_detachFromEngine = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'detachFromEngine',
        r'(Lio/flutter/plugin/common/BinaryMessenger;)V',
      );

  static final _detachFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun detachFromEngine(messenger: io.flutter.plugin.common.BinaryMessenger): kotlin.Unit`
  void detachFromEngine(BinaryMessenger binaryMessenger) {
    final _$$selfRef = reference;
    final _$binaryMessenger = binaryMessenger.reference;
    _detachFromEngine(
      _$$selfRef.pointer,
      _id_detachFromEngine.pointer,
      _$binaryMessenger.pointer,
    ).check();
  }

  static final _id_setHasReplay = FlutterSessionReplayBridge._class
      .instanceMethodId(r'setHasReplay', r'(Ljava/lang/String;Z)V');

  static final _setHasReplay =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun setHasReplay(viewId: kotlin.String, hasReplay: kotlin.Boolean): kotlin.Unit`
  void setHasReplay(jni$_.JString string, core$_.bool z) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _setHasReplay(
      _$$selfRef.pointer,
      _id_setHasReplay.pointer,
      _$string.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_setRecordCount = FlutterSessionReplayBridge._class
      .instanceMethodId(r'setRecordCount', r'(Ljava/lang/String;I)V');

  static final _setRecordCount =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun setRecordCount(viewId: kotlin.String, recordCount: kotlin.Int): kotlin.Unit`
  void setRecordCount(jni$_.JString string, core$_.int i) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _setRecordCount(
      _$$selfRef.pointer,
      _id_setRecordCount.pointer,
      _$string.pointer,
      i,
    ).check();
  }

  static final _id_writeSegment = FlutterSessionReplayBridge._class
      .instanceMethodId(r'writeSegment', r'(Ljava/lang/String;)V');

  static final _writeSegment =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun writeSegment(segment: kotlin.String): kotlin.Unit`
  void writeSegment(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _writeSegment(
      _$$selfRef.pointer,
      _id_writeSegment.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_telemetryDebug = FlutterSessionReplayBridge._class
      .instanceMethodId(r'telemetryDebug', r'(Ljava/lang/String;)V');

  static final _telemetryDebug =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun telemetryDebug(message: kotlin.String): kotlin.Unit`
  void telemetryDebug(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _telemetryDebug(
      _$$selfRef.pointer,
      _id_telemetryDebug.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_telemetryError = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'telemetryError',
        r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
      );

  static final _telemetryError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun telemetryError(message: kotlin.String, stack: kotlin.String, kind: kotlin.String): kotlin.Unit`
  void telemetryError(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    _telemetryError(
      _$$selfRef.pointer,
      _id_telemetryError.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).check();
  }

  static final _id_saveImageForProcessing = FlutterSessionReplayBridge._class
      .instanceMethodId(
        r'saveImageForProcessing',
        r'(ILjava/nio/ByteBuffer;II)V',
      );

  static final _saveImageForProcessing =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public fun saveImageForProcessing(resourceId: kotlin.Int, imageData: java.nio.ByteBuffer, width: kotlin.Int, height: kotlin.Int): kotlin.Unit`
  void saveImageForProcessing(
    core$_.int i,
    jni$_.JByteBuffer byteBuffer,
    core$_.int i1,
    core$_.int i2,
  ) {
    final _$$selfRef = reference;
    final _$byteBuffer = byteBuffer.reference;
    _saveImageForProcessing(
      _$$selfRef.pointer,
      _id_saveImageForProcessing.pointer,
      i,
      _$byteBuffer.pointer,
      i1,
      i2,
    ).check();
  }

  static final _id_resourceIdForKey = FlutterSessionReplayBridge._class
      .instanceMethodId(r'resourceIdForKey', r'(I)Ljava/lang/String;');

  static final _resourceIdForKey =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun resourceIdForKey(resourceId: kotlin.Int): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? resourceIdForKey(core$_.int i) {
    final _$$selfRef = reference;
    return _resourceIdForKey(
      _$$selfRef.pointer,
      _id_resourceIdForKey.pointer,
      i,
    ).object<jni$_.JString?>();
  }
}

final class $FlutterSessionReplayBridge$Type$
    extends jni$_.JType<FlutterSessionReplayBridge> {
  @jni$_.internal
  const $FlutterSessionReplayBridge$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/FlutterSessionReplayBridge;';
}

/// from: `com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature`
///
/// WARNING: DefaultFlutterSessionReplayFeature is a stub. To generate bindings for this class, include
/// com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature in your config's classes list.
///
extension type DefaultFlutterSessionReplayFeature._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultFlutterSessionReplayFeature> type =
      $DefaultFlutterSessionReplayFeature$Type$();
}

final class $DefaultFlutterSessionReplayFeature$Type$
    extends jni$_.JType<DefaultFlutterSessionReplayFeature> {
  @jni$_.internal
  const $DefaultFlutterSessionReplayFeature$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature;';
}

/// from: `io.flutter.plugin.common.BinaryMessenger`
///
/// WARNING: BinaryMessenger is a stub. To generate bindings for this class, include
/// io.flutter.plugin.common.BinaryMessenger in your config's classes list.
///
extension type BinaryMessenger._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<BinaryMessenger> type = $BinaryMessenger$Type$();
}

final class $BinaryMessenger$Type$ extends jni$_.JType<BinaryMessenger> {
  @jni$_.internal
  const $BinaryMessenger$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/flutter/plugin/common/BinaryMessenger;';
}

/// from: `com.datadog.android.api.feature.FeatureSdkCore`
///
/// WARNING: FeatureSdkCore is a stub. To generate bindings for this class, include
/// com.datadog.android.api.feature.FeatureSdkCore in your config's classes list.
///
extension type FeatureSdkCore._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<FeatureSdkCore> type = $FeatureSdkCore$Type$();
}

final class $FeatureSdkCore$Type$ extends jni$_.JType<FeatureSdkCore> {
  @jni$_.internal
  const $FeatureSdkCore$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/datadog/android/api/feature/FeatureSdkCore;';
}

/// from: `kotlin.jvm.internal.DefaultConstructorMarker`
///
/// WARNING: DefaultConstructorMarker is a stub. To generate bindings for this class, include
/// kotlin.jvm.internal.DefaultConstructorMarker in your config's classes list.
///
extension type DefaultConstructorMarker._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultConstructorMarker> type =
      $DefaultConstructorMarker$Type$();
}

final class $DefaultConstructorMarker$Type$
    extends jni$_.JType<DefaultConstructorMarker> {
  @jni$_.internal
  const $DefaultConstructorMarker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/jvm/internal/DefaultConstructorMarker;';
}

/// from: `com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature$RumContext`
///
/// WARNING: DefaultFlutterSessionReplayFeature$$RumContext is a stub. To generate bindings for this class, include
/// com.datadoghq.flutter.sessionreplay.feature.DefaultFlutterSessionReplayFeature$RumContext in your config's classes list.
///
extension type DefaultFlutterSessionReplayFeature$$RumContext._(
  jni$_.JObject _$this
)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultFlutterSessionReplayFeature$$RumContext>
  type = $DefaultFlutterSessionReplayFeature$$RumContext$Type$();
}

final class $DefaultFlutterSessionReplayFeature$$RumContext$Type$
    extends jni$_.JType<DefaultFlutterSessionReplayFeature$$RumContext> {
  @jni$_.internal
  const $DefaultFlutterSessionReplayFeature$$RumContext$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/datadoghq/flutter/sessionreplay/feature/DefaultFlutterSessionReplayFeature$RumContext;';
}
