// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

const _$objcVersionCheck = objc.ObjCVersionCheck(9, 5);
@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)
      >
    >,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _9m2kop_wrapBlockingBlock_xtuoz7(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)>
  >
  directInvoke,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _9m2kop_wrapListenerBlock_xtuoz7(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
);

/// FlutterRUMCoreContext
extension type FlutterRUMCoreContext._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterRUMCoreContext] that points to the same underlying object as [other].
  FlutterRUMCoreContext.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterRUMCoreContext] that wraps the given raw object pointer.
  FlutterRUMCoreContext.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterRUMCoreContext].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_FlutterRUMCoreContext,
        );

  /// alloc
  static FlutterRUMCoreContext alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_FlutterRUMCoreContext,
      _sel_alloc,
    );
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static FlutterRUMCoreContext allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterRUMCoreContext,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

extension FlutterRUMCoreContext$Methods on FlutterRUMCoreContext {
  /// applicationID
  objc.NSString get applicationID {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_applicationID);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// sessionID
  objc.NSString get sessionID {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_sessionID);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// setApplicationID:
  set applicationID(objc.NSString value) {
    final _$$ref = object$.ref;
    final _$$ref$1 = value.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_setApplicationID_,
      _$$ref$1.pointer,
    );
  }

  /// setSessionID:
  set sessionID(objc.NSString value) {
    final _$$ref = object$.ref;
    final _$$ref$1 = value.ref;
    _objc_msgSend_xtuoz7(_$$ref.pointer, _sel_setSessionID_, _$$ref$1.pointer);
  }

  /// setViewID:
  set viewID(objc.NSString? value) {
    final _$$ref = object$.ref;
    final _$$ref$1 = value?.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_setViewID_,
      _$$ref$1?.pointer ?? ffi.nullptr,
    );
  }

  /// viewID
  objc.NSString? get viewID {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_viewID);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

/// FlutterSessionReplay
extension type FlutterSessionReplay._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterSessionReplay] that points to the same underlying object as [other].
  FlutterSessionReplay.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterSessionReplay] that wraps the given raw object pointer.
  FlutterSessionReplay.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterSessionReplay].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_FlutterSessionReplay,
        );

  /// alloc
  static FlutterSessionReplay alloc() {
    final $ret = _objc_msgSend_151sglz(_class_FlutterSessionReplay, _sel_alloc);
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static FlutterSessionReplay allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterSessionReplay,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static FlutterSessionReplay new$() {
    final $ret = _objc_msgSend_151sglz(_class_FlutterSessionReplay, _sel_new);
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of FlutterSessionReplay constructed with the default `new` method.
  FlutterSessionReplay() : this.as(new$().object$);
}

extension FlutterSessionReplay$Methods on FlutterSessionReplay {
  /// enableWith:
  void enableWith(FlutterSessionReplayConfiguration configuration) {
    final _$$ref = object$.ref;
    final _$$ref$1 = configuration.ref;
    _objc_msgSend_xtuoz7(_$$ref.pointer, _sel_enableWith_, _$$ref$1.pointer);
  }

  /// engineToken
  objc.NSString get engineToken {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_engineToken);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// init
  FlutterSessionReplay init() {
    final _$$ref = object$.ref;
    objc.checkOsVersionInternal(
      'FlutterSessionReplay.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _$$ref.retainAndReturnPointer(),
      _sel_init,
    );
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// postTelemetryDebugWithId:message:
  void postTelemetryDebugWithId(
    objc.NSString id, {
    required objc.NSString message,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = id.ref;
    final _$$ref$2 = message.ref;
    _objc_msgSend_pfv6jd(
      _$$ref.pointer,
      _sel_postTelemetryDebugWithId_message_,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
    );
  }

  /// postTelemetryErrorWithMessage:kind:stackTrace:
  void postTelemetryErrorWithMessage(
    objc.NSString message, {
    required objc.NSString kind,
    required objc.NSString stackTrace,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = message.ref;
    final _$$ref$2 = kind.ref;
    final _$$ref$3 = stackTrace.ref;
    _objc_msgSend_r8gdi7(
      _$$ref.pointer,
      _sel_postTelemetryErrorWithMessage_kind_stackTrace_,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
      _$$ref$3.pointer,
    );
  }

  /// resourceIdForKey:
  objc.NSString? resourceIdForKey(int key) {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_qugqlf(
      _$$ref.pointer,
      _sel_resourceIdForKey_,
      key,
    );
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// saveImageForProcessingWithResourceKey:width:height:data:
  void saveImageForProcessingWithResourceKey(
    int resourceKey, {
    required int width,
    required int height,
    required objc.NSData data,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = data.ref;
    _objc_msgSend_g5idq5(
      _$$ref.pointer,
      _sel_saveImageForProcessingWithResourceKey_width_height_data_,
      resourceKey,
      width,
      height,
      _$$ref$1.pointer,
    );
  }

  /// setEmbedded:
  void setEmbedded(bool isEmbedded) {
    final _$$ref = object$.ref;
    _objc_msgSend_1s56lr9(_$$ref.pointer, _sel_setEmbedded_, isEmbedded);
  }

  /// setHasReplayWithHasReplay:
  void setHasReplayWithHasReplay(bool hasReplay) {
    final _$$ref = object$.ref;
    _objc_msgSend_1s56lr9(
      _$$ref.pointer,
      _sel_setHasReplayWithHasReplay_,
      hasReplay,
    );
  }

  /// setRecordCountFor:count:
  void setRecordCountFor(objc.NSString viewId, {required int count}) {
    final _$$ref = object$.ref;
    final _$$ref$1 = viewId.ref;
    _objc_msgSend_1nvl641(
      _$$ref.pointer,
      _sel_setRecordCountFor_count_,
      _$$ref$1.pointer,
      count,
    );
  }

  /// writeSegmentWithSegment:
  void writeSegmentWithSegment(objc.NSString segmentJson) {
    final _$$ref = object$.ref;
    final _$$ref$1 = segmentJson.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_writeSegmentWithSegment_,
      _$$ref$1.pointer,
    );
  }
}

/// FlutterSessionReplayConfiguration
extension type FlutterSessionReplayConfiguration._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterSessionReplayConfiguration] that points to the same underlying object as [other].
  FlutterSessionReplayConfiguration.as(objc.ObjCObject other)
    : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterSessionReplayConfiguration] that wraps the given raw object pointer.
  FlutterSessionReplayConfiguration.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterSessionReplayConfiguration].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_FlutterSessionReplayConfiguration,
        );

  /// alloc
  static FlutterSessionReplayConfiguration alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_FlutterSessionReplayConfiguration,
      _sel_alloc,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static FlutterSessionReplayConfiguration allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterSessionReplayConfiguration,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

extension FlutterSessionReplayConfiguration$Methods
    on FlutterSessionReplayConfiguration {
  /// customEndpoint
  objc.NSURL? get customEndpoint {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_customEndpoint);
    return $ret.address == 0
        ? null
        : objc.NSURL.fromPointer($ret, retain: true, release: true);
  }

  /// initWithCustomEndpoint:onContextChanged:
  FlutterSessionReplayConfiguration initWithCustomEndpoint(
    objc.NSURL? customEndpoint, {
    objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>? onContextChanged,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = customEndpoint?.ref;
    final _$$ref$2 = onContextChanged?.ref;
    final $ret = _objc_msgSend_r0bo0s(
      _$$ref.retainAndReturnPointer(),
      _sel_initWithCustomEndpoint_onContextChanged_,
      _$$ref$1?.pointer ?? ffi.nullptr,
      _$$ref$2?.pointer ?? ffi.nullptr,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// setCustomEndpoint:
  set customEndpoint(objc.NSURL? value) {
    final _$$ref = object$.ref;
    final _$$ref$1 = value?.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_setCustomEndpoint_,
      _$$ref$1?.pointer ?? ffi.nullptr,
    );
  }
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>`.
abstract final class ObjCBlock_ffiVoid_FlutterRUMCoreContext {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> fromFunction(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    objc.newClosureBlock(_closureCallable, (
      ffi.Pointer<objc.ObjCObjectImpl> arg0,
    ) {
      return fn(
        arg0.address == 0
            ? null
            : FlutterRUMCoreContext.fromPointer(
                arg0,
                retain: true,
                release: true,
              ),
      );
    }, keepIsolateAlive),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This block can be invoked from any thread, but only supports void
  /// functions, and is not run synchronously. Async functions (ie returning
  /// Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> listener(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
      objc.newBlockPort(_9m2kop_wrapListenerBlock_xtuoz7, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_hwt9h3.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions (ie returning Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> blocking(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
      objc.newBlockingBlockPort(_9m2kop_wrapBlockingBlock_xtuoz7, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_hwt9h3.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
        >
      >()
      .asFunction<void Function(ffi.Pointer<objc.ObjCObjectImpl>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>`.
extension ObjCBlock_ffiVoid_FlutterRUMCoreContext$CallExtension
    on objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> {
  void call(FlutterRUMCoreContext? arg0) {
    final _$$ref = arg0?.ref;
    return ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<objc.ObjCObjectImpl> arg0,
            )
          >
        >()
        .asFunction<
          void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >()(ref.pointer, _$$ref?.pointer ?? ffi.nullptr);
  }
}

extension type _BlockArgs_hwt9h3._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [_BlockArgs_hwt9h3] that points to the same underlying object as [other].
  _BlockArgs_hwt9h3.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [_BlockArgs_hwt9h3] that wraps the given raw object pointer.
  _BlockArgs_hwt9h3.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [_BlockArgs_hwt9h3].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class__BlockArgs_hwt9h3,
        );
}

extension _BlockArgs_hwt9h3$Methods on _BlockArgs_hwt9h3 {
  FlutterRUMCoreContext? get arg0 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg0);
    return $ret.address == 0
        ? null
        : FlutterRUMCoreContext.fromPointer($ret, retain: true, release: true);
  }
}

@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_FlutterRUMCoreContext',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_FlutterRUMCoreContext_raw;
final _class_FlutterRUMCoreContext = objc.getClass(
  "FlutterRUMCoreContext",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_FlutterRUMCoreContext_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_FlutterSessionReplay',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_FlutterSessionReplay_raw;
final _class_FlutterSessionReplay = objc.getClass(
  "FlutterSessionReplay",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_FlutterSessionReplay_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$_FlutterSessionReplayConfiguration',
)
external ffi.Pointer<objc.ObjCObjectImpl>
_class_FlutterSessionReplayConfiguration_raw;
final _class_FlutterSessionReplayConfiguration = objc.getClass(
  "FlutterSessionReplayConfiguration",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_FlutterSessionReplayConfiguration_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__9m2kop_BlockArgs_xtuoz7',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class__BlockArgs_hwt9h3_raw;
final _class__BlockArgs_hwt9h3 = objc.getClass(
  "_9m2kop_BlockArgs_xtuoz7",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class__BlockArgs_hwt9h3_raw,
  ).cast(),
);
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_1nvl641 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        int,
      )
    >();
final _objc_msgSend_1s56lr9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
final _objc_msgSend_g5idq5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
          ffi.Long,
          ffi.Long,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        int,
        int,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_pfv6jd = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_qugqlf = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_r0bo0s = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
final _objc_msgSend_r8gdi7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_applicationID = objc.registerName("applicationID");
late final _sel_arg0 = objc.registerName("arg0");
late final _sel_customEndpoint = objc.registerName("customEndpoint");
late final _sel_enableWith_ = objc.registerName("enableWith:");
late final _sel_engineToken = objc.registerName("engineToken");
late final _sel_init = objc.registerName("init");
late final _sel_initWithCustomEndpoint_onContextChanged_ = objc.registerName(
  "initWithCustomEndpoint:onContextChanged:",
);
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_new = objc.registerName("new");
late final _sel_postTelemetryDebugWithId_message_ = objc.registerName(
  "postTelemetryDebugWithId:message:",
);
late final _sel_postTelemetryErrorWithMessage_kind_stackTrace_ = objc
    .registerName("postTelemetryErrorWithMessage:kind:stackTrace:");
late final _sel_resourceIdForKey_ = objc.registerName("resourceIdForKey:");
late final _sel_saveImageForProcessingWithResourceKey_width_height_data_ = objc
    .registerName("saveImageForProcessingWithResourceKey:width:height:data:");
late final _sel_sessionID = objc.registerName("sessionID");
late final _sel_setApplicationID_ = objc.registerName("setApplicationID:");
late final _sel_setCustomEndpoint_ = objc.registerName("setCustomEndpoint:");
late final _sel_setEmbedded_ = objc.registerName("setEmbedded:");
late final _sel_setHasReplayWithHasReplay_ = objc.registerName(
  "setHasReplayWithHasReplay:",
);
late final _sel_setRecordCountFor_count_ = objc.registerName(
  "setRecordCountFor:count:",
);
late final _sel_setSessionID_ = objc.registerName("setSessionID:");
late final _sel_setViewID_ = objc.registerName("setViewID:");
late final _sel_viewID = objc.registerName("viewID");
late final _sel_writeSegmentWithSegment_ = objc.registerName(
  "writeSegmentWithSegment:",
);
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
