// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(ffi.Pointer<objc.ObjCBlockImpl>)
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl>
_datadog_session_replay_bridge_wrapListenerBlock_xtuoz7(
  ffi.Pointer<objc.ObjCBlockImpl> block,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl>
_datadog_session_replay_bridge_wrapBlockingBlock_xtuoz7(
  ffi.Pointer<objc.ObjCBlockImpl> block,
  ffi.Pointer<objc.ObjCBlockImpl> listnerBlock,
  ffi.Pointer<objc.DOBJC_Context> context,
);

late final _class_FlutterRUMCoreContext = objc.getClass(
  "FlutterRUMCoreContext",
);
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_sessionID = objc.registerName("sessionID");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setSessionID_ = objc.registerName("setSessionID:");
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_viewID = objc.registerName("viewID");
late final _sel_setViewID_ = objc.registerName("setViewID:");
late final _sel_applicationID = objc.registerName("applicationID");
late final _sel_setApplicationID_ = objc.registerName("setApplicationID:");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_init = objc.registerName("init");
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// FlutterRUMCoreContext
extension type FlutterRUMCoreContext._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterRUMCoreContext] that points to the same underlying object as [other].
  FlutterRUMCoreContext.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterRUMCoreContext] that wraps the given raw object pointer.
  FlutterRUMCoreContext.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterRUMCoreContext].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_FlutterRUMCoreContext,
  );

  /// alloc
  static FlutterRUMCoreContext alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_FlutterRUMCoreContext,
      _sel_alloc,
    );
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static FlutterRUMCoreContext allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterRUMCoreContext,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// new
  static FlutterRUMCoreContext new$() {
    final $ret = _objc_msgSend_151sglz(_class_FlutterRUMCoreContext, _sel_new);
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of FlutterRUMCoreContext constructed with the default `new` method.
  FlutterRUMCoreContext() : this.as(new$().object$);
}

extension FlutterRUMCoreContext$Methods on FlutterRUMCoreContext {
  /// applicationID
  objc.NSString get applicationID {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_applicationID);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// init
  FlutterRUMCoreContext init() {
    objc.checkOsVersionInternal(
      'FlutterRUMCoreContext.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return FlutterRUMCoreContext.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// sessionID
  objc.NSString get sessionID {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_sessionID);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// setApplicationID:
  set applicationID(objc.NSString value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setApplicationID_,
      value.ref.pointer,
    );
  }

  /// setSessionID:
  set sessionID(objc.NSString value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setSessionID_,
      value.ref.pointer,
    );
  }

  /// setViewID:
  set viewID(objc.NSString? value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setViewID_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  /// viewID
  objc.NSString? get viewID {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_viewID);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

late final _class_FlutterSessionReplay = objc.getClass("FlutterSessionReplay");
late final _class_FlutterSessionReplayConfiguration = objc.getClass(
  "FlutterSessionReplayConfiguration",
);
late final _sel_customEndpoint = objc.registerName("customEndpoint");
late final _sel_setCustomEndpoint_ = objc.registerName("setCustomEndpoint:");

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>`.
abstract final class ObjCBlock_ffiVoid_FlutterRUMCoreContext {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> fromFunction(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) => fn(
        arg0.address == 0
            ? null
            : FlutterRUMCoreContext.fromPointer(
                arg0,
                retain: true,
                release: true,
              ),
      ),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This is based on FFI's NativeCallable.listener, and has the same
  /// capabilities and limitations. This block can be invoked from any thread,
  /// but only supports void functions, and is not run synchronously. See
  /// NativeCallable.listener for more details.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> listener(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _listenerCallable.nativeFunction.cast(),
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) => fn(
        arg0.address == 0
            ? null
            : FlutterRUMCoreContext.fromPointer(
                arg0,
                retain: false,
                release: true,
              ),
      ),
      keepIsolateAlive,
    );
    final wrapper = _datadog_session_replay_bridge_wrapListenerBlock_xtuoz7(
      raw,
    );
    objc.objectRelease(raw.cast());
    return objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> blocking(
    void Function(FlutterRUMCoreContext?) fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _blockingCallable.nativeFunction.cast(),
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) => fn(
        arg0.address == 0
            ? null
            : FlutterRUMCoreContext.fromPointer(
                arg0,
                retain: false,
                release: true,
              ),
      ),
      keepIsolateAlive,
    );
    final rawListener = objc.newClosureBlock(
      _blockingListenerCallable.nativeFunction.cast(),
      (ffi.Pointer<objc.ObjCObjectImpl> arg0) => fn(
        arg0.address == 0
            ? null
            : FlutterRUMCoreContext.fromPointer(
                arg0,
                retain: false,
                release: true,
              ),
      ),
      keepIsolateAlive,
    );
    final wrapper = _datadog_session_replay_bridge_wrapBlockingBlock_xtuoz7(
      raw,
      rawListener,
      objc.objCContext,
    );
    objc.objectRelease(raw.cast());
    objc.objectRelease(rawListener.cast());
    return objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  static void _listenerTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) {
    (objc.getBlockClosure(block)
        as void Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
    objc.objectRelease(block.cast());
  }

  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<objc.ObjCObjectImpl>,
    )
  >
  _listenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >.listener(_listenerTrampoline)
        ..keepIsolateAlive = false;
  static void _blockingTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> waiter,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) {
    try {
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
    } catch (e) {
    } finally {
      objc.signalWaiter(waiter);
      objc.objectRelease(block.cast());
    }
  }

  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<objc.ObjCObjectImpl>,
    )
  >
  _blockingCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >.isolateLocal(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static ffi.NativeCallable<
    ffi.Void Function(
      ffi.Pointer<objc.ObjCBlockImpl>,
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<objc.ObjCObjectImpl>,
    )
  >
  _blockingListenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >.listener(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
        >
      >()
      .asFunction<void Function(ffi.Pointer<objc.ObjCObjectImpl>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>`.
extension ObjCBlock_ffiVoid_FlutterRUMCoreContext$CallExtension
    on objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)> {
  void call(FlutterRUMCoreContext? arg0) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<objc.ObjCObjectImpl> arg0,
          )
        >
      >()
      .asFunction<
        void Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0?.ref.pointer ?? ffi.nullptr);
}

late final _sel_initWithCustomEndpoint_onContextChanged_ = objc.registerName(
  "initWithCustomEndpoint:onContextChanged:",
);
final _objc_msgSend_r0bo0s = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();

/// FlutterSessionReplayConfiguration
extension type FlutterSessionReplayConfiguration._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterSessionReplayConfiguration] that points to the same underlying object as [other].
  FlutterSessionReplayConfiguration.as(objc.ObjCObject other)
    : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterSessionReplayConfiguration] that wraps the given raw object pointer.
  FlutterSessionReplayConfiguration.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterSessionReplayConfiguration].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_FlutterSessionReplayConfiguration,
  );

  /// alloc
  static FlutterSessionReplayConfiguration alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_FlutterSessionReplayConfiguration,
      _sel_alloc,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// allocWithZone:
  static FlutterSessionReplayConfiguration allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterSessionReplayConfiguration,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// new
  static FlutterSessionReplayConfiguration new$() {
    final $ret = _objc_msgSend_151sglz(
      _class_FlutterSessionReplayConfiguration,
      _sel_new,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of FlutterSessionReplayConfiguration constructed with the default `new` method.
  FlutterSessionReplayConfiguration() : this.as(new$().object$);
}

extension FlutterSessionReplayConfiguration$Methods
    on FlutterSessionReplayConfiguration {
  /// customEndpoint
  objc.NSURL? get customEndpoint {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_customEndpoint,
    );
    return $ret.address == 0
        ? null
        : objc.NSURL.fromPointer($ret, retain: true, release: true);
  }

  /// init
  FlutterSessionReplayConfiguration init() {
    objc.checkOsVersionInternal(
      'FlutterSessionReplayConfiguration.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// initWithCustomEndpoint:onContextChanged:
  FlutterSessionReplayConfiguration initWithCustomEndpoint(
    objc.NSURL? customEndpoint, {
    objc.ObjCBlock<ffi.Void Function(FlutterRUMCoreContext?)>? onContextChanged,
  }) {
    final $ret = _objc_msgSend_r0bo0s(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCustomEndpoint_onContextChanged_,
      customEndpoint?.ref.pointer ?? ffi.nullptr,
      onContextChanged?.ref.pointer ?? ffi.nullptr,
    );
    return FlutterSessionReplayConfiguration.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// setCustomEndpoint:
  set customEndpoint(objc.NSURL? value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setCustomEndpoint_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }
}

late final _sel_enableWith_ = objc.registerName("enableWith:");
late final _sel_setHasReplayWithHasReplay_ = objc.registerName(
  "setHasReplayWithHasReplay:",
);
final _objc_msgSend_1s56lr9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
late final _sel_setRecordCountFor_count_ = objc.registerName(
  "setRecordCountFor:count:",
);
final _objc_msgSend_1nvl641 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        int,
      )
    >();
late final _sel_writeSegmentWithSegment_ = objc.registerName(
  "writeSegmentWithSegment:",
);
late final _sel_postTelemetryDebugWithId_message_ = objc.registerName(
  "postTelemetryDebugWithId:message:",
);
final _objc_msgSend_pfv6jd = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_postTelemetryErrorWithMessage_kind_stackTrace_ = objc
    .registerName("postTelemetryErrorWithMessage:kind:stackTrace:");
final _objc_msgSend_r8gdi7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_saveImageForProcessingWithResourceKey_width_height_data_ = objc
    .registerName("saveImageForProcessingWithResourceKey:width:height:data:");
final _objc_msgSend_g5idq5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
          ffi.Long,
          ffi.Long,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        int,
        int,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_resourceIdForKey_ = objc.registerName("resourceIdForKey:");
final _objc_msgSend_qugqlf = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();

/// FlutterSessionReplay
extension type FlutterSessionReplay._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FlutterSessionReplay] that points to the same underlying object as [other].
  FlutterSessionReplay.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FlutterSessionReplay] that wraps the given raw object pointer.
  FlutterSessionReplay.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FlutterSessionReplay].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_FlutterSessionReplay,
  );

  /// alloc
  static FlutterSessionReplay alloc() {
    final $ret = _objc_msgSend_151sglz(_class_FlutterSessionReplay, _sel_alloc);
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static FlutterSessionReplay allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FlutterSessionReplay,
      _sel_allocWithZone_,
      zone,
    );
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static FlutterSessionReplay new$() {
    final $ret = _objc_msgSend_151sglz(_class_FlutterSessionReplay, _sel_new);
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of FlutterSessionReplay constructed with the default `new` method.
  FlutterSessionReplay() : this.as(new$().object$);
}

extension FlutterSessionReplay$Methods on FlutterSessionReplay {
  /// enableWith:
  void enableWith(FlutterSessionReplayConfiguration configuration) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_enableWith_,
      configuration.ref.pointer,
    );
  }

  /// init
  FlutterSessionReplay init() {
    objc.checkOsVersionInternal(
      'FlutterSessionReplay.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return FlutterSessionReplay.fromPointer($ret, retain: false, release: true);
  }

  /// postTelemetryDebugWithId:message:
  void postTelemetryDebugWithId(
    objc.NSString id, {
    required objc.NSString message,
  }) {
    _objc_msgSend_pfv6jd(
      object$.ref.pointer,
      _sel_postTelemetryDebugWithId_message_,
      id.ref.pointer,
      message.ref.pointer,
    );
  }

  /// postTelemetryErrorWithMessage:kind:stackTrace:
  void postTelemetryErrorWithMessage(
    objc.NSString message, {
    required objc.NSString kind,
    required objc.NSString stackTrace,
  }) {
    _objc_msgSend_r8gdi7(
      object$.ref.pointer,
      _sel_postTelemetryErrorWithMessage_kind_stackTrace_,
      message.ref.pointer,
      kind.ref.pointer,
      stackTrace.ref.pointer,
    );
  }

  /// resourceIdForKey:
  objc.NSString? resourceIdForKey(int key) {
    final $ret = _objc_msgSend_qugqlf(
      object$.ref.pointer,
      _sel_resourceIdForKey_,
      key,
    );
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// saveImageForProcessingWithResourceKey:width:height:data:
  void saveImageForProcessingWithResourceKey(
    int resourceKey, {
    required int width,
    required int height,
    required objc.NSData data,
  }) {
    _objc_msgSend_g5idq5(
      object$.ref.pointer,
      _sel_saveImageForProcessingWithResourceKey_width_height_data_,
      resourceKey,
      width,
      height,
      data.ref.pointer,
    );
  }

  /// setHasReplayWithHasReplay:
  void setHasReplayWithHasReplay(bool hasReplay) {
    _objc_msgSend_1s56lr9(
      object$.ref.pointer,
      _sel_setHasReplayWithHasReplay_,
      hasReplay,
    );
  }

  /// setRecordCountFor:count:
  void setRecordCountFor(objc.NSString viewId, {required int count}) {
    _objc_msgSend_1nvl641(
      object$.ref.pointer,
      _sel_setRecordCountFor_count_,
      viewId.ref.pointer,
      count,
    );
  }

  /// writeSegmentWithSegment:
  void writeSegmentWithSegment(objc.NSString segmentJson) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_writeSegmentWithSegment_,
      segmentJson.ref.pointer,
    );
  }
}
