name: datadog_dio_example
description: "An example of how to use Datadog's Dio interceptor."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  transparent_image: ^2.0.1
  datadog_flutter_plugin:
    path: ../../datadog_flutter_plugin
  datadog_dio:
    path: ../
  datadog_common_test:
    path: ../../datadog_common_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  collection: ^1.18.0

flutter:
  uses-material-design: true

  assets:
    - .env

dependency_overrides:
  datadog_flutter_plugin:
    path: ../../datadog_flutter_plugin
