// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class dd_sdk_cpp {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  dd_sdk_cpp(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  dd_sdk_cpp.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int imaxabs(
    int __n,
  ) {
    return _imaxabs(
      __n,
    );
  }

  late final _imaxabsPtr =
      _lookup<ffi.NativeFunction<intmax_t Function(intmax_t)>>('imaxabs');
  late final _imaxabs = _imaxabsPtr.asFunction<int Function(int)>(isLeaf: true);

  imaxdiv_t imaxdiv(
    int __numer,
    int __denom,
  ) {
    return _imaxdiv(
      __numer,
      __denom,
    );
  }

  late final _imaxdivPtr =
      _lookup<ffi.NativeFunction<imaxdiv_t Function(intmax_t, intmax_t)>>(
          'imaxdiv');
  late final _imaxdiv =
      _imaxdivPtr.asFunction<imaxdiv_t Function(int, int)>(isLeaf: true);

  int strtoimax(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoimax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoimaxPtr = _lookup<
      ffi.NativeFunction<
          intmax_t Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>>('strtoimax');
  late final _strtoimax = _strtoimaxPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int)>(isLeaf: true);

  int strtoumax(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoumax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoumaxPtr = _lookup<
      ffi.NativeFunction<
          uintmax_t Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>>('strtoumax');
  late final _strtoumax = _strtoumaxPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int)>(isLeaf: true);

  int wcstoimax(
    ffi.Pointer<__gwchar_t> __nptr,
    ffi.Pointer<ffi.Pointer<__gwchar_t>> __endptr,
    int __base,
  ) {
    return _wcstoimax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _wcstoimaxPtr = _lookup<
      ffi.NativeFunction<
          intmax_t Function(ffi.Pointer<__gwchar_t>,
              ffi.Pointer<ffi.Pointer<__gwchar_t>>, ffi.Int)>>('wcstoimax');
  late final _wcstoimax = _wcstoimaxPtr.asFunction<
      int Function(ffi.Pointer<__gwchar_t>,
          ffi.Pointer<ffi.Pointer<__gwchar_t>>, int)>(isLeaf: true);

  int wcstoumax(
    ffi.Pointer<__gwchar_t> __nptr,
    ffi.Pointer<ffi.Pointer<__gwchar_t>> __endptr,
    int __base,
  ) {
    return _wcstoumax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _wcstoumaxPtr = _lookup<
      ffi.NativeFunction<
          uintmax_t Function(ffi.Pointer<__gwchar_t>,
              ffi.Pointer<ffi.Pointer<__gwchar_t>>, ffi.Int)>>('wcstoumax');
  late final _wcstoumax = _wcstoumaxPtr.asFunction<
      int Function(ffi.Pointer<__gwchar_t>,
          ffi.Pointer<ffi.Pointer<__gwchar_t>>, int)>(isLeaf: true);

  int dd_timestamp_ns(
    int nanoseconds_since_epoch,
  ) {
    return _dd_timestamp_ns(
      nanoseconds_since_epoch,
    );
  }

  late final _dd_timestamp_nsPtr =
      _lookup<ffi.NativeFunction<dd_timestamp_t Function(ffi.Int64)>>(
          'dd_timestamp_ns');
  late final _dd_timestamp_ns =
      _dd_timestamp_nsPtr.asFunction<int Function(int)>(isLeaf: true);

  int dd_timestamp_ms(
    int milliseconds_since_epoch,
  ) {
    return _dd_timestamp_ms(
      milliseconds_since_epoch,
    );
  }

  late final _dd_timestamp_msPtr =
      _lookup<ffi.NativeFunction<dd_timestamp_t Function(ffi.Int64)>>(
          'dd_timestamp_ms');
  late final _dd_timestamp_ms =
      _dd_timestamp_msPtr.asFunction<int Function(int)>(isLeaf: true);

  int dd_timestamp_seconds(
    int seconds_since_epoch,
  ) {
    return _dd_timestamp_seconds(
      seconds_since_epoch,
    );
  }

  late final _dd_timestamp_secondsPtr =
      _lookup<ffi.NativeFunction<dd_timestamp_t Function(ffi.Int64)>>(
          'dd_timestamp_seconds');
  late final _dd_timestamp_seconds =
      _dd_timestamp_secondsPtr.asFunction<int Function(int)>(isLeaf: true);

  void dd_uuid_init(
    ffi.Pointer<dd_uuid_t> value,
  ) {
    return _dd_uuid_init(
      value,
    );
  }

  late final _dd_uuid_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_uuid_t>)>>(
          'dd_uuid_init');
  late final _dd_uuid_init = _dd_uuid_initPtr
      .asFunction<void Function(ffi.Pointer<dd_uuid_t>)>(isLeaf: true);

  void dd_uuid_random(
    ffi.Pointer<dd_uuid_t> value,
  ) {
    return _dd_uuid_random(
      value,
    );
  }

  late final _dd_uuid_randomPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_uuid_t>)>>(
          'dd_uuid_random');
  late final _dd_uuid_random = _dd_uuid_randomPtr
      .asFunction<void Function(ffi.Pointer<dd_uuid_t>)>(isLeaf: true);

  void dd_uuid_set(
    ffi.Pointer<dd_uuid_t> value,
    ffi.Pointer<ffi.Uint8> bytes,
  ) {
    return _dd_uuid_set(
      value,
      bytes,
    );
  }

  late final _dd_uuid_setPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_uuid_t>, ffi.Pointer<ffi.Uint8>)>>('dd_uuid_set');
  late final _dd_uuid_set = _dd_uuid_setPtr.asFunction<
      void Function(
          ffi.Pointer<dd_uuid_t>, ffi.Pointer<ffi.Uint8>)>(isLeaf: true);

  bool dd_uuid_parse(
    ffi.Pointer<dd_uuid_t> value,
    ffi.Pointer<ffi.Char> s,
  ) {
    return _dd_uuid_parse(
      value,
      s,
    );
  }

  late final _dd_uuid_parsePtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              ffi.Pointer<dd_uuid_t>, ffi.Pointer<ffi.Char>)>>('dd_uuid_parse');
  late final _dd_uuid_parse = _dd_uuid_parsePtr
      .asFunction<bool Function(ffi.Pointer<dd_uuid_t>, ffi.Pointer<ffi.Char>)>(
          isLeaf: true);

  void dd_uuid_to_string(
    ffi.Pointer<dd_uuid_t> value,
    ffi.Pointer<ffi.Char> out_s,
  ) {
    return _dd_uuid_to_string(
      value,
      out_s,
    );
  }

  late final _dd_uuid_to_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_uuid_t>,
              ffi.Pointer<ffi.Char>)>>('dd_uuid_to_string');
  late final _dd_uuid_to_string = _dd_uuid_to_stringPtr
      .asFunction<void Function(ffi.Pointer<dd_uuid_t>, ffi.Pointer<ffi.Char>)>(
          isLeaf: true);

  bool dd_uuid_is_zero(
    ffi.Pointer<dd_uuid_t> value,
  ) {
    return _dd_uuid_is_zero(
      value,
    );
  }

  late final _dd_uuid_is_zeroPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<dd_uuid_t>)>>(
          'dd_uuid_is_zero');
  late final _dd_uuid_is_zero = _dd_uuid_is_zeroPtr
      .asFunction<bool Function(ffi.Pointer<dd_uuid_t>)>(isLeaf: true);

  dd_attribute_t dd_attribute_null() {
    return _dd_attribute_null();
  }

  late final _dd_attribute_nullPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function()>>(
          'dd_attribute_null');
  late final _dd_attribute_null =
      _dd_attribute_nullPtr.asFunction<dd_attribute_t Function()>(isLeaf: true);

  dd_attribute_t dd_attribute_bool(
    bool value,
  ) {
    return _dd_attribute_bool(
      value,
    );
  }

  late final _dd_attribute_boolPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Bool)>>(
          'dd_attribute_bool');
  late final _dd_attribute_bool = _dd_attribute_boolPtr
      .asFunction<dd_attribute_t Function(bool)>(isLeaf: true);

  dd_attribute_t dd_attribute_int(
    int value,
  ) {
    return _dd_attribute_int(
      value,
    );
  }

  late final _dd_attribute_intPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Int64)>>(
          'dd_attribute_int');
  late final _dd_attribute_int = _dd_attribute_intPtr
      .asFunction<dd_attribute_t Function(int)>(isLeaf: true);

  dd_attribute_t dd_attribute_uint(
    int value,
  ) {
    return _dd_attribute_uint(
      value,
    );
  }

  late final _dd_attribute_uintPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Uint64)>>(
          'dd_attribute_uint');
  late final _dd_attribute_uint = _dd_attribute_uintPtr
      .asFunction<dd_attribute_t Function(int)>(isLeaf: true);

  dd_attribute_t dd_attribute_timestamp(
    int value,
  ) {
    return _dd_attribute_timestamp(
      value,
    );
  }

  late final _dd_attribute_timestampPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(dd_timestamp_t)>>(
          'dd_attribute_timestamp');
  late final _dd_attribute_timestamp = _dd_attribute_timestampPtr
      .asFunction<dd_attribute_t Function(int)>(isLeaf: true);

  dd_attribute_t dd_attribute_double(
    double value,
  ) {
    return _dd_attribute_double(
      value,
    );
  }

  late final _dd_attribute_doublePtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Double)>>(
          'dd_attribute_double');
  late final _dd_attribute_double = _dd_attribute_doublePtr
      .asFunction<dd_attribute_t Function(double)>(isLeaf: true);

  dd_attribute_t dd_attribute_uuid(
    dd_uuid_t value,
  ) {
    return _dd_attribute_uuid(
      value,
    );
  }

  late final _dd_attribute_uuidPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(dd_uuid_t)>>(
          'dd_attribute_uuid');
  late final _dd_attribute_uuid = _dd_attribute_uuidPtr
      .asFunction<dd_attribute_t Function(dd_uuid_t)>(isLeaf: true);

  dd_attribute_t dd_attribute_string(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_attribute_string(
      value,
    );
  }

  late final _dd_attribute_stringPtr = _lookup<
          ffi.NativeFunction<dd_attribute_t Function(ffi.Pointer<ffi.Char>)>>(
      'dd_attribute_string');
  late final _dd_attribute_string = _dd_attribute_stringPtr
      .asFunction<dd_attribute_t Function(ffi.Pointer<ffi.Char>)>(isLeaf: true);

  dd_attribute_t dd_attribute_array(
    int initial_capacity,
  ) {
    return _dd_attribute_array(
      initial_capacity,
    );
  }

  late final _dd_attribute_arrayPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Size)>>(
          'dd_attribute_array');
  late final _dd_attribute_array = _dd_attribute_arrayPtr
      .asFunction<dd_attribute_t Function(int)>(isLeaf: true);

  dd_attribute_t dd_attribute_object(
    int initial_capacity,
  ) {
    return _dd_attribute_object(
      initial_capacity,
    );
  }

  late final _dd_attribute_objectPtr =
      _lookup<ffi.NativeFunction<dd_attribute_t Function(ffi.Size)>>(
          'dd_attribute_object');
  late final _dd_attribute_object = _dd_attribute_objectPtr
      .asFunction<dd_attribute_t Function(int)>(isLeaf: true);

  void dd_attribute_set_null(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_set_null(
      attribute,
    );
  }

  late final _dd_attribute_set_nullPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_set_null');
  late final _dd_attribute_set_null = _dd_attribute_set_nullPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_attribute_set_bool(
    ffi.Pointer<dd_attribute_t> attribute,
    bool value,
  ) {
    return _dd_attribute_set_bool(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_boolPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_attribute_t>, ffi.Bool)>>('dd_attribute_set_bool');
  late final _dd_attribute_set_bool = _dd_attribute_set_boolPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, bool)>(
          isLeaf: true);

  void dd_attribute_set_int(
    ffi.Pointer<dd_attribute_t> attribute,
    int value,
  ) {
    return _dd_attribute_set_int(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_attribute_t>, ffi.Int64)>>('dd_attribute_set_int');
  late final _dd_attribute_set_int = _dd_attribute_set_intPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  void dd_attribute_set_uint(
    ffi.Pointer<dd_attribute_t> attribute,
    int value,
  ) {
    return _dd_attribute_set_uint(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_uintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Uint64)>>('dd_attribute_set_uint');
  late final _dd_attribute_set_uint = _dd_attribute_set_uintPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  void dd_attribute_set_timestamp(
    ffi.Pointer<dd_attribute_t> attribute,
    int value,
  ) {
    return _dd_attribute_set_timestamp(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_timestampPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              dd_timestamp_t)>>('dd_attribute_set_timestamp');
  late final _dd_attribute_set_timestamp = _dd_attribute_set_timestampPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  void dd_attribute_set_double(
    ffi.Pointer<dd_attribute_t> attribute,
    double value,
  ) {
    return _dd_attribute_set_double(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Double)>>('dd_attribute_set_double');
  late final _dd_attribute_set_double = _dd_attribute_set_doublePtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, double)>(
          isLeaf: true);

  void dd_attribute_set_uuid(
    ffi.Pointer<dd_attribute_t> attribute,
    dd_uuid_t value,
  ) {
    return _dd_attribute_set_uuid(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              dd_uuid_t)>>('dd_attribute_set_uuid');
  late final _dd_attribute_set_uuid = _dd_attribute_set_uuidPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, dd_uuid_t)>(
          isLeaf: true);

  void dd_attribute_set_string(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_attribute_set_string(
      attribute,
      value,
    );
  }

  late final _dd_attribute_set_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>>('dd_attribute_set_string');
  late final _dd_attribute_set_string = _dd_attribute_set_stringPtr.asFunction<
      void Function(
          ffi.Pointer<dd_attribute_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_attribute_init_array(
    ffi.Pointer<dd_attribute_t> attribute,
    int initial_capacity,
  ) {
    return _dd_attribute_init_array(
      attribute,
      initial_capacity,
    );
  }

  late final _dd_attribute_init_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Size)>>('dd_attribute_init_array');
  late final _dd_attribute_init_array = _dd_attribute_init_arrayPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  void dd_attribute_init_object(
    ffi.Pointer<dd_attribute_t> attribute,
    int initial_capacity,
  ) {
    return _dd_attribute_init_object(
      attribute,
      initial_capacity,
    );
  }

  late final _dd_attribute_init_objectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Size)>>('dd_attribute_init_object');
  late final _dd_attribute_init_object = _dd_attribute_init_objectPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  dd_attribute_t dd_attribute_copy(
    ffi.Pointer<dd_attribute_t> other,
  ) {
    return _dd_attribute_copy(
      other,
    );
  }

  late final _dd_attribute_copyPtr = _lookup<
      ffi.NativeFunction<
          dd_attribute_t Function(
              ffi.Pointer<dd_attribute_t>)>>('dd_attribute_copy');
  late final _dd_attribute_copy = _dd_attribute_copyPtr
      .asFunction<dd_attribute_t Function(ffi.Pointer<dd_attribute_t>)>(
          isLeaf: true);

  void dd_attribute_free(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_free(
      attribute,
    );
  }

  late final _dd_attribute_freePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_free');
  late final _dd_attribute_free = _dd_attribute_freePtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  bool dd_attribute_get_bool(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_bool(
      attribute,
    );
  }

  late final _dd_attribute_get_boolPtr = _lookup<
          ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_get_bool');
  late final _dd_attribute_get_bool = _dd_attribute_get_boolPtr
      .asFunction<bool Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  int dd_attribute_get_int(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_int(
      attribute,
    );
  }

  late final _dd_attribute_get_intPtr = _lookup<
          ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_get_int');
  late final _dd_attribute_get_int = _dd_attribute_get_intPtr
      .asFunction<int Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  int dd_attribute_get_uint(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_uint(
      attribute,
    );
  }

  late final _dd_attribute_get_uintPtr = _lookup<
          ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_get_uint');
  late final _dd_attribute_get_uint = _dd_attribute_get_uintPtr
      .asFunction<int Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  int dd_attribute_get_timestamp(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_timestamp(
      attribute,
    );
  }

  late final _dd_attribute_get_timestampPtr = _lookup<
      ffi.NativeFunction<
          dd_timestamp_t Function(
              ffi.Pointer<dd_attribute_t>)>>('dd_attribute_get_timestamp');
  late final _dd_attribute_get_timestamp = _dd_attribute_get_timestampPtr
      .asFunction<int Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  double dd_attribute_get_double(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_double(
      attribute,
    );
  }

  late final _dd_attribute_get_doublePtr = _lookup<
          ffi.NativeFunction<ffi.Double Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_get_double');
  late final _dd_attribute_get_double = _dd_attribute_get_doublePtr
      .asFunction<double Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  dd_uuid_t dd_attribute_get_uuid(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_uuid(
      attribute,
    );
  }

  late final _dd_attribute_get_uuidPtr = _lookup<
          ffi.NativeFunction<dd_uuid_t Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_get_uuid');
  late final _dd_attribute_get_uuid = _dd_attribute_get_uuidPtr
      .asFunction<dd_uuid_t Function(ffi.Pointer<dd_attribute_t>)>(
          isLeaf: true);

  ffi.Pointer<ffi.Char> dd_attribute_get_string(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_get_string(
      attribute,
    );
  }

  late final _dd_attribute_get_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dd_attribute_t>)>>('dd_attribute_get_string');
  late final _dd_attribute_get_string = _dd_attribute_get_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dd_attribute_t>)>(
          isLeaf: true);

  int dd_attribute_array_len(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_array_len(
      attribute,
    );
  }

  late final _dd_attribute_array_lenPtr = _lookup<
          ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_array_len');
  late final _dd_attribute_array_len = _dd_attribute_array_lenPtr
      .asFunction<int Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  dd_attribute_t dd_attribute_array_get(
    ffi.Pointer<dd_attribute_t> attribute,
    int index,
  ) {
    return _dd_attribute_array_get(
      attribute,
      index,
    );
  }

  late final _dd_attribute_array_getPtr = _lookup<
      ffi.NativeFunction<
          dd_attribute_t Function(
              ffi.Pointer<dd_attribute_t>, ffi.Int)>>('dd_attribute_array_get');
  late final _dd_attribute_array_get = _dd_attribute_array_getPtr
      .asFunction<dd_attribute_t Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  void dd_attribute_array_clear(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_array_clear(
      attribute,
    );
  }

  late final _dd_attribute_array_clearPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_array_clear');
  late final _dd_attribute_array_clear = _dd_attribute_array_clearPtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_attribute_array_push(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<dd_attribute_t> item,
  ) {
    return _dd_attribute_array_push(
      attribute,
      item,
    );
  }

  late final _dd_attribute_array_pushPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<dd_attribute_t>)>>('dd_attribute_array_push');
  late final _dd_attribute_array_push = _dd_attribute_array_pushPtr.asFunction<
      void Function(ffi.Pointer<dd_attribute_t>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_attribute_array_reserve(
    ffi.Pointer<dd_attribute_t> attribute,
    int capacity,
  ) {
    return _dd_attribute_array_reserve(
      attribute,
      capacity,
    );
  }

  late final _dd_attribute_array_reservePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Size)>>('dd_attribute_array_reserve');
  late final _dd_attribute_array_reserve = _dd_attribute_array_reservePtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  int dd_attribute_object_property_count(
    ffi.Pointer<dd_attribute_t> attribute,
  ) {
    return _dd_attribute_object_property_count(
      attribute,
    );
  }

  late final _dd_attribute_object_property_countPtr = _lookup<
          ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_object_property_count');
  late final _dd_attribute_object_property_count =
      _dd_attribute_object_property_countPtr
          .asFunction<int Function(ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  int dd_attribute_object_property_find(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_attribute_object_property_find(
      attribute,
      name,
    );
  }

  late final _dd_attribute_object_property_findPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>>('dd_attribute_object_property_find');
  late final _dd_attribute_object_property_find =
      _dd_attribute_object_property_findPtr.asFunction<
              int Function(ffi.Pointer<dd_attribute_t>, ffi.Pointer<ffi.Char>)>(
          isLeaf: true);

  ffi.Pointer<ffi.Char> dd_attribute_object_name_at(
    ffi.Pointer<dd_attribute_t> attribute,
    int index,
  ) {
    return _dd_attribute_object_name_at(
      attribute,
      index,
    );
  }

  late final _dd_attribute_object_name_atPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<dd_attribute_t>,
              ffi.Int)>>('dd_attribute_object_name_at');
  late final _dd_attribute_object_name_at =
      _dd_attribute_object_name_atPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dd_attribute_t>, int)>(isLeaf: true);

  dd_attribute_t dd_attribute_object_value_at(
    ffi.Pointer<dd_attribute_t> attribute,
    int index,
  ) {
    return _dd_attribute_object_value_at(
      attribute,
      index,
    );
  }

  late final _dd_attribute_object_value_atPtr = _lookup<
      ffi.NativeFunction<
          dd_attribute_t Function(ffi.Pointer<dd_attribute_t>,
              ffi.Int)>>('dd_attribute_object_value_at');
  late final _dd_attribute_object_value_at = _dd_attribute_object_value_atPtr
      .asFunction<dd_attribute_t Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  dd_attribute_t dd_attribute_object_property_get(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_attribute_object_property_get(
      attribute,
      name,
    );
  }

  late final _dd_attribute_object_property_getPtr = _lookup<
      ffi.NativeFunction<
          dd_attribute_t Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>>('dd_attribute_object_property_get');
  late final _dd_attribute_object_property_get =
      _dd_attribute_object_property_getPtr.asFunction<
          dd_attribute_t Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_attribute_object_property_set(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<dd_attribute_t> value,
  ) {
    return _dd_attribute_object_property_set(
      attribute,
      name,
      value,
    );
  }

  late final _dd_attribute_object_property_setPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<dd_attribute_t>,
                  ffi.Pointer<ffi.Char>, ffi.Pointer<dd_attribute_t>)>>(
      'dd_attribute_object_property_set');
  late final _dd_attribute_object_property_set =
      _dd_attribute_object_property_setPtr.asFunction<
          void Function(ffi.Pointer<dd_attribute_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_attribute_object_property_delete(
    ffi.Pointer<dd_attribute_t> attribute,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_attribute_object_property_delete(
      attribute,
      name,
    );
  }

  late final _dd_attribute_object_property_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>>('dd_attribute_object_property_delete');
  late final _dd_attribute_object_property_delete =
      _dd_attribute_object_property_deletePtr.asFunction<
          void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_attribute_object_reserve(
    ffi.Pointer<dd_attribute_t> attribute,
    int capacity,
  ) {
    return _dd_attribute_object_reserve(
      attribute,
      capacity,
    );
  }

  late final _dd_attribute_object_reservePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_attribute_t>,
              ffi.Size)>>('dd_attribute_object_reserve');
  late final _dd_attribute_object_reserve = _dd_attribute_object_reservePtr
      .asFunction<void Function(ffi.Pointer<dd_attribute_t>, int)>(
          isLeaf: true);

  /// Default dd_diagnostic_handler_t implementation: prints all messages to stderr,
  /// prefixed with '[DATADOG <level>]'.
  void dd_stderr_diagnostic_handler(
    ffi.Pointer<dd_diagnostic_message_t> message,
    ffi.Pointer<ffi.Void> arg1,
  ) {
    return _dd_stderr_diagnostic_handler(
      message,
      arg1,
    );
  }

  late final _dd_stderr_diagnostic_handlerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_diagnostic_message_t>,
              ffi.Pointer<ffi.Void>)>>('dd_stderr_diagnostic_handler');
  late final _dd_stderr_diagnostic_handler =
      _dd_stderr_diagnostic_handlerPtr.asFunction<
          void Function(ffi.Pointer<dd_diagnostic_message_t>,
              ffi.Pointer<ffi.Void>)>(isLeaf: true);

  /// Initializes a new dd_core_config_t with the set of values that are required for the
  /// SDK to function.
  ///
  /// @param client_token The client token associated with your application.
  /// @param service The name of the application, service, or component being monitored.
  /// @param in_env The environment in which this application is running, e.g. 'prod',
  /// 'dev', 'staging', 'testing', etc.
  void dd_core_config_init(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Char> client_token,
    ffi.Pointer<ffi.Char> service,
    ffi.Pointer<ffi.Char> env,
  ) {
    return dd_core_config_init_func(
      config,
      client_token,
      service,
      env,
    );
  }

  late final _dd_core_config_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dd_core_config_init');
  late final dd_core_config_init_func = _dd_core_config_initPtr.asFunction<
      void Function(ffi.Pointer<dd_core_config_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Supplies a callback function that will be invoked whenever the SDK emits a diagnostic
  /// message whose level meets or exceeds the configured diagnostic threshold.
  ///
  /// The default handler is dd_stderr_diagnostic_handler, which prints to stderr. If this
  /// value is set to NULL, all diagnostic messages will be silently dropped.
  void dd_core_config_set_diagnostic_handler(
    ffi.Pointer<dd_core_config_t> config,
    dd_diagnostic_handler_t value,
  ) {
    return _dd_core_config_set_diagnostic_handler(
      config,
      value,
    );
  }

  late final _dd_core_config_set_diagnostic_handlerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<dd_core_config_t>, dd_diagnostic_handler_t)>>(
      'dd_core_config_set_diagnostic_handler');
  late final _dd_core_config_set_diagnostic_handler =
      _dd_core_config_set_diagnostic_handlerPtr.asFunction<
          void Function(ffi.Pointer<dd_core_config_t>,
              dd_diagnostic_handler_t)>(isLeaf: true);

  /// Sets an arbitrary value that will be supplied to all invocations of the diagnostic
  /// handler callback. The default handler (dd_stderr_diagnostic_handler) will never read
  /// this value.
  void dd_core_config_set_diagnostic_handler_userdata(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Void> value,
  ) {
    return _dd_core_config_set_diagnostic_handler_userdata(
      config,
      value,
    );
  }

  late final _dd_core_config_set_diagnostic_handler_userdataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<dd_core_config_t>, ffi.Pointer<ffi.Void>)>>(
      'dd_core_config_set_diagnostic_handler_userdata');
  late final _dd_core_config_set_diagnostic_handler_userdata =
      _dd_core_config_set_diagnostic_handler_userdataPtr.asFunction<
          void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Void>)>(isLeaf: true);

  /// Sets the threshold for diagnostic logging: any message whose level meets or exceeds
  /// this value will be passed to the configured diagnostic handler callback.
  void dd_core_config_set_diagnostic_threshold(
    ffi.Pointer<dd_core_config_t> config,
    dd_diagnostic_level_t value,
  ) {
    return _dd_core_config_set_diagnostic_threshold(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_diagnostic_thresholdPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_diagnostic_threshold');
  late final _dd_core_config_set_diagnostic_threshold =
      _dd_core_config_set_diagnostic_thresholdPtr
          .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
              isLeaf: true);

  /// Sets the tracking consent value used on SDK startup. Defaults to PENDING.
  ///
  /// If the user's tracking consent changes after the SDK is initialized, call
  /// dd_core_set_tracking_consent() to update it at runtime.
  void dd_core_config_set_initial_tracking_consent(
    ffi.Pointer<dd_core_config_t> config,
    dd_tracking_consent_t value,
  ) {
    return _dd_core_config_set_initial_tracking_consent(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_initial_tracking_consentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_initial_tracking_consent');
  late final _dd_core_config_set_initial_tracking_consent =
      _dd_core_config_set_initial_tracking_consentPtr
          .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
              isLeaf: true);

  /// Sets the site (i.e. Datadog datacenter) where data for your organization is stored.
  /// Defaults to us1.
  void dd_core_config_set_site(
    ffi.Pointer<dd_core_config_t> config,
    dd_site_t value,
  ) {
    return _dd_core_config_set_site(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_sitePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_site');
  late final _dd_core_config_set_site = _dd_core_config_set_sitePtr
      .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
          isLeaf: true);

  /// Sets the client token value, overriding the value passed to dd_core_config_init().
  void dd_core_config_set_client_token(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_core_config_set_client_token(
      config,
      value,
    );
  }

  late final _dd_core_config_set_client_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_core_config_set_client_token');
  late final _dd_core_config_set_client_token =
      _dd_core_config_set_client_tokenPtr.asFunction<
          void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the 'service' value, overriding the value passed to dd_core_config_init().
  void dd_core_config_set_service(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_core_config_set_service(
      config,
      value,
    );
  }

  late final _dd_core_config_set_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_core_config_set_service');
  late final _dd_core_config_set_service =
      _dd_core_config_set_servicePtr.asFunction<
          void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the 'env' value, overriding the value passed to dd_core_config_init().
  void dd_core_config_set_env(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_core_config_set_env(
      config,
      value,
    );
  }

  late final _dd_core_config_set_envPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_core_config_set_env');
  late final _dd_core_config_set_env = _dd_core_config_set_envPtr.asFunction<
      void Function(
          ffi.Pointer<dd_core_config_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the 'version' value, identifying the version of your applicating that's being
  /// monitored.
  void dd_core_config_set_application_version(
    ffi.Pointer<dd_core_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_core_config_set_application_version(
      config,
      value,
    );
  }

  late final _dd_core_config_set_application_versionPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<dd_core_config_t>, ffi.Pointer<ffi.Char>)>>(
      'dd_core_config_set_application_version');
  late final _dd_core_config_set_application_version =
      _dd_core_config_set_application_versionPtr.asFunction<
          void Function(ffi.Pointer<dd_core_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Configures the SDK's batch size, which informs how quickly it will consider a batch
  /// of event data ready for upload.
  void dd_core_config_set_batch_size(
    ffi.Pointer<dd_core_config_t> config,
    dd_batch_size_t value,
  ) {
    return _dd_core_config_set_batch_size(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_batch_sizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_batch_size');
  late final _dd_core_config_set_batch_size = _dd_core_config_set_batch_sizePtr
      .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
          isLeaf: true);

  /// Configures the SDK's upload frequency, which informs how frequently it will check for
  /// new batches of events to upload.
  void dd_core_config_set_upload_frequency(
    ffi.Pointer<dd_core_config_t> config,
    dd_upload_frequency_t value,
  ) {
    return _dd_core_config_set_upload_frequency(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_upload_frequencyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_upload_frequency');
  late final _dd_core_config_set_upload_frequency =
      _dd_core_config_set_upload_frequencyPtr
          .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
              isLeaf: true);

  /// Configures the SDK's batch processing level, which limits the number of batches that
  /// will be uploaded in a given upload cycle.
  void dd_core_config_set_batch_processing_level(
    ffi.Pointer<dd_core_config_t> config,
    dd_batch_processing_level_t value,
  ) {
    return _dd_core_config_set_batch_processing_level(
      config,
      value.value,
    );
  }

  late final _dd_core_config_set_batch_processing_levelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_config_t>,
              ffi.UnsignedInt)>>('dd_core_config_set_batch_processing_level');
  late final _dd_core_config_set_batch_processing_level =
      _dd_core_config_set_batch_processing_levelPtr
          .asFunction<void Function(ffi.Pointer<dd_core_config_t>, int)>(
              isLeaf: true);

  ffi.Pointer<dd_core_t> dd_core_create(
    ffi.Pointer<dd_core_config_t> config,
  ) {
    return _dd_core_create(
      config,
    );
  }

  late final _dd_core_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dd_core_t> Function(
              ffi.Pointer<dd_core_config_t>)>>('dd_core_create');
  late final _dd_core_create = _dd_core_createPtr.asFunction<
      ffi.Pointer<dd_core_t> Function(
          ffi.Pointer<dd_core_config_t>)>(isLeaf: true);

  void dd_core_destroy(
    ffi.Pointer<dd_core_t> core,
  ) {
    return _dd_core_destroy(
      core,
    );
  }

  late final _dd_core_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_core_t>)>>(
          'dd_core_destroy');
  late final _dd_core_destroy = _dd_core_destroyPtr
      .asFunction<void Function(ffi.Pointer<dd_core_t>)>(isLeaf: true);

  void dd_core_set_tracking_consent(
    ffi.Pointer<dd_core_t> core,
    dd_tracking_consent_t value,
  ) {
    return _dd_core_set_tracking_consent(
      core,
      value.value,
    );
  }

  late final _dd_core_set_tracking_consentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_core_t>,
              ffi.UnsignedInt)>>('dd_core_set_tracking_consent');
  late final _dd_core_set_tracking_consent = _dd_core_set_tracking_consentPtr
      .asFunction<void Function(ffi.Pointer<dd_core_t>, int)>(isLeaf: true);

  bool dd_core_start(
    ffi.Pointer<dd_core_t> core,
  ) {
    return _dd_core_start(
      core,
    );
  }

  late final _dd_core_startPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<dd_core_t>)>>(
          'dd_core_start');
  late final _dd_core_start = _dd_core_startPtr
      .asFunction<bool Function(ffi.Pointer<dd_core_t>)>(isLeaf: true);

  void dd_core_stop(
    ffi.Pointer<dd_core_t> core,
  ) {
    return _dd_core_stop(
      core,
    );
  }

  late final _dd_core_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_core_t>)>>(
          'dd_core_stop');
  late final _dd_core_stop = _dd_core_stopPtr
      .asFunction<void Function(ffi.Pointer<dd_core_t>)>(isLeaf: true);

  /// Initializes a dd_logger_config_t with default settings.
  void dd_logger_config_init(
    ffi.Pointer<dd_logger_config_t> config,
  ) {
    return _dd_logger_config_init(
      config,
    );
  }

  late final _dd_logger_config_initPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<dd_logger_config_t>)>>(
      'dd_logger_config_init');
  late final _dd_logger_config_init = _dd_logger_config_initPtr
      .asFunction<void Function(ffi.Pointer<dd_logger_config_t>)>(isLeaf: true);

  /// Sets the remote sample rate to a value between 0.0 and 100.0, indicating what
  /// percentage of log events should be sampled. At 100.0, all messages are sent to
  /// intake; at 0.0, all messages are discarded. Default is 100.0.
  void dd_logger_config_set_remote_sample_rate(
    ffi.Pointer<dd_logger_config_t> config,
    double value,
  ) {
    return _dd_logger_config_set_remote_sample_rate(
      config,
      value,
    );
  }

  late final _dd_logger_config_set_remote_sample_ratePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Float)>>('dd_logger_config_set_remote_sample_rate');
  late final _dd_logger_config_set_remote_sample_rate =
      _dd_logger_config_set_remote_sample_ratePtr
          .asFunction<void Function(ffi.Pointer<dd_logger_config_t>, double)>(
              isLeaf: true);

  /// Sets the service name to be used on messages emitted by a logger. If omitted, the
  /// logger will use the service name configured globally via dd_core_config_t.
  ///
  /// Config stores a copy of provided string value. If the given string value exceeds
  /// DATADOG_MAX_SERVICE_NAME_LEN, it will be truncated to that length. Both NULL and ""
  /// will be interepreted as no value, causing the logger to use the default service name.
  void dd_logger_config_set_service(
    ffi.Pointer<dd_logger_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_logger_config_set_service(
      config,
      value,
    );
  }

  late final _dd_logger_config_set_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_config_set_service');
  late final _dd_logger_config_set_service =
      _dd_logger_config_set_servicePtr.asFunction<
          void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the name used to identify a logger in messages emitted by that logger. If
  /// omitted, no 'logger.name' property will be present on log events.
  ///
  /// Config stores a copy of provided string value. If the given string value exceeds
  /// DATADOG_MAX_LOGGER_NAME_LEN, it will be truncated to that length. Both NULL and ""
  /// will be interpreted as no value.
  void dd_logger_config_set_name(
    ffi.Pointer<dd_logger_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_logger_config_set_name(
      config,
      value,
    );
  }

  late final _dd_logger_config_set_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_config_set_name');
  late final _dd_logger_config_set_name =
      _dd_logger_config_set_namePtr.asFunction<
          void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the minimum log level at which messages will be sent to intake. Only messages at
  /// or above this level will be considered for sampling; all messages below that level
  /// will be dropped. Defaults to DD_LOG_LEVEL_DEBUG, meaning all messages will be sent to
  /// intake.
  void dd_logger_config_set_remote_log_threshold(
    ffi.Pointer<dd_logger_config_t> config,
    dd_log_level_t value,
  ) {
    return _dd_logger_config_set_remote_log_threshold(
      config,
      value.value,
    );
  }

  late final _dd_logger_config_set_remote_log_thresholdPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.UnsignedInt)>>('dd_logger_config_set_remote_log_threshold');
  late final _dd_logger_config_set_remote_log_threshold =
      _dd_logger_config_set_remote_log_thresholdPtr
          .asFunction<void Function(ffi.Pointer<dd_logger_config_t>, int)>(
              isLeaf: true);

  /// Sets the initial number of custom attributes for which memory will be preallocated on
  /// logger creation. At the default of 0, does not reserve space for custom attributes.
  ///
  /// Custom attributes may be freely added beyond this limit. Setting an initial capacity
  /// is simply a means of optimizing memory allocations based on expected usage.
  void dd_logger_config_set_initial_attribute_capacity(
    ffi.Pointer<dd_logger_config_t> config,
    int value,
  ) {
    return _dd_logger_config_set_initial_attribute_capacity(
      config,
      value,
    );
  }

  late final _dd_logger_config_set_initial_attribute_capacityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Size)>>('dd_logger_config_set_initial_attribute_capacity');
  late final _dd_logger_config_set_initial_attribute_capacity =
      _dd_logger_config_set_initial_attribute_capacityPtr
          .asFunction<void Function(ffi.Pointer<dd_logger_config_t>, int)>(
              isLeaf: true);

  /// Controls whether log events generated by this logger will be enriched with current
  /// RUM application state, provided that RUM is in use. Defaults to true.
  void dd_logger_config_set_enrich_with_rum_context(
    ffi.Pointer<dd_logger_config_t> config,
    bool value,
  ) {
    return _dd_logger_config_set_enrich_with_rum_context(
      config,
      value,
    );
  }

  late final _dd_logger_config_set_enrich_with_rum_contextPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_config_t>,
              ffi.Bool)>>('dd_logger_config_set_enrich_with_rum_context');
  late final _dd_logger_config_set_enrich_with_rum_context =
      _dd_logger_config_set_enrich_with_rum_contextPtr
          .asFunction<void Function(ffi.Pointer<dd_logger_config_t>, bool)>(
              isLeaf: true);

  /// Registers the logging feature with the core of the Datadog SDK. MUST be matched with
  /// a call to dd_logging_destroy().
  ffi.Pointer<dd_logging_t> dd_logging_init(
    ffi.Pointer<dd_core_t> core,
  ) {
    return _dd_logging_init(
      core,
    );
  }

  late final _dd_logging_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dd_logging_t> Function(
              ffi.Pointer<dd_core_t>)>>('dd_logging_init');
  late final _dd_logging_init = _dd_logging_initPtr
      .asFunction<ffi.Pointer<dd_logging_t> Function(ffi.Pointer<dd_core_t>)>(
          isLeaf: true);

  /// Frees all memory allocated for for the logging feature reference, rendering it no
  /// longer usable. May be called at any time.
  void dd_logging_destroy(
    ffi.Pointer<dd_logging_t> logging,
  ) {
    return _dd_logging_destroy(
      logging,
    );
  }

  late final _dd_logging_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_logging_t>)>>(
          'dd_logging_destroy');
  late final _dd_logging_destroy = _dd_logging_destroyPtr
      .asFunction<void Function(ffi.Pointer<dd_logging_t>)>(isLeaf: true);

  /// Adds or updates a global attribute value that will be included with all log messages
  /// emitted by all loggers.
  void dd_logging_add_attribute(
    ffi.Pointer<dd_logging_t> logging,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<dd_attribute_t> value,
  ) {
    return _dd_logging_add_attribute(
      logging,
      name,
      value,
    );
  }

  late final _dd_logging_add_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logging_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logging_add_attribute');
  late final _dd_logging_add_attribute =
      _dd_logging_add_attributePtr.asFunction<
          void Function(ffi.Pointer<dd_logging_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Removes a global attribute value, if one has been previously added with the given
  /// name.
  void dd_logging_remove_attribute(
    ffi.Pointer<dd_logging_t> logging,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_logging_remove_attribute(
      logging,
      name,
    );
  }

  late final _dd_logging_remove_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logging_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logging_remove_attribute');
  late final _dd_logging_remove_attribute =
      _dd_logging_remove_attributePtr.asFunction<
          void Function(
              ffi.Pointer<dd_logging_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Creates and returns a new logger with the given configuration. You MUST call
  /// dd_logger_destroy() when finished with the logger.
  ///
  /// If config is NULL, the default configuration values will be used.
  ffi.Pointer<dd_logger_t> dd_logger_create(
    ffi.Pointer<dd_logging_t> logging,
    ffi.Pointer<dd_logger_config_t> config,
  ) {
    return _dd_logger_create(
      logging,
      config,
    );
  }

  late final _dd_logger_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dd_logger_t> Function(ffi.Pointer<dd_logging_t>,
              ffi.Pointer<dd_logger_config_t>)>>('dd_logger_create');
  late final _dd_logger_create = _dd_logger_createPtr.asFunction<
      ffi.Pointer<dd_logger_t> Function(ffi.Pointer<dd_logging_t>,
          ffi.Pointer<dd_logger_config_t>)>(isLeaf: true);

  /// Frees all memory allocated for the given logger.
  void dd_logger_destroy(
    ffi.Pointer<dd_logger_t> logger,
  ) {
    return _dd_logger_destroy(
      logger,
    );
  }

  late final _dd_logger_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_logger_t>)>>(
          'dd_logger_destroy');
  late final _dd_logger_destroy = _dd_logger_destroyPtr
      .asFunction<void Function(ffi.Pointer<dd_logger_t>)>(isLeaf: true);

  /// Adds or updates a logger-level attribute value that will be included with all
  /// messages emitted by this logger. If a logger-level attribute shares its name with a
  /// global attribute, the logger-level attribute will take precedence.
  void dd_logger_add_attribute(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<dd_attribute_t> value,
  ) {
    return _dd_logger_add_attribute(
      logger,
      name,
      value,
    );
  }

  late final _dd_logger_add_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_add_attribute');
  late final _dd_logger_add_attribute = _dd_logger_add_attributePtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Removes a logger-level attribute value, if one has been previously added with the
  /// given name.
  void dd_logger_remove_attribute(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_logger_remove_attribute(
      logger,
      name,
    );
  }

  late final _dd_logger_remove_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_remove_attribute');
  late final _dd_logger_remove_attribute =
      _dd_logger_remove_attributePtr.asFunction<
          void Function(
              ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Emits a log message at the given level.
  void dd_logger_log(
    ffi.Pointer<dd_logger_t> logger,
    dd_log_level_t level,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_log(
      logger,
      level.value,
      message,
    );
  }

  late final _dd_logger_logPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.UnsignedInt,
              ffi.Pointer<ffi.Char>)>>('dd_logger_log');
  late final _dd_logger_log = _dd_logger_logPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, int, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_debug(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_debug(
      logger,
      message,
    );
  }

  late final _dd_logger_debugPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_debug');
  late final _dd_logger_debug = _dd_logger_debugPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_info(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_info(
      logger,
      message,
    );
  }

  late final _dd_logger_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_info');
  late final _dd_logger_info = _dd_logger_infoPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_notice(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_notice(
      logger,
      message,
    );
  }

  late final _dd_logger_noticePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_notice');
  late final _dd_logger_notice = _dd_logger_noticePtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_warn(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_warn(
      logger,
      message,
    );
  }

  late final _dd_logger_warnPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_warn');
  late final _dd_logger_warn = _dd_logger_warnPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_error(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_error(
      logger,
      message,
    );
  }

  late final _dd_logger_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_error');
  late final _dd_logger_error = _dd_logger_errorPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  void dd_logger_critical(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dd_logger_critical(
      logger,
      message,
    );
  }

  late final _dd_logger_criticalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>,
              ffi.Pointer<ffi.Char>)>>('dd_logger_critical');
  late final _dd_logger_critical = _dd_logger_criticalPtr.asFunction<
      void Function(
          ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Emits a log message at the given level, with the given set of message-level
  /// attributes included.
  ///
  /// If attributes has type DD_VALUE_TYPE_OBJECT, each of its named values will be
  /// included in the resulting log event, taking precedence over global and logger-level
  /// attributes in case of name conflict. If attributes is a value of any other type, it
  /// will be ignored.
  void dd_logger_log_obj(
    ffi.Pointer<dd_logger_t> logger,
    dd_log_level_t level,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_log_obj(
      logger,
      level.value,
      message,
      attributes,
    );
  }

  late final _dd_logger_log_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_logger_t>,
              ffi.UnsignedInt,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_log_obj');
  late final _dd_logger_log_obj = _dd_logger_log_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, int, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_info_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_info_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_info_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_info_obj');
  late final _dd_logger_info_obj = _dd_logger_info_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_debug_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_debug_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_debug_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_debug_obj');
  late final _dd_logger_debug_obj = _dd_logger_debug_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_notice_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_notice_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_notice_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_notice_obj');
  late final _dd_logger_notice_obj = _dd_logger_notice_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_warn_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_warn_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_warn_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_warn_obj');
  late final _dd_logger_warn_obj = _dd_logger_warn_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_error_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_error_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_error_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_error_obj');
  late final _dd_logger_error_obj = _dd_logger_error_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  void dd_logger_critical_obj(
    ffi.Pointer<dd_logger_t> logger,
    ffi.Pointer<ffi.Char> message,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_logger_critical_obj(
      logger,
      message,
      attributes,
    );
  }

  late final _dd_logger_critical_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_logger_critical_obj');
  late final _dd_logger_critical_obj = _dd_logger_critical_objPtr.asFunction<
      void Function(ffi.Pointer<dd_logger_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Initializes a dd_rum_config_t with all required settings.
  ///
  /// @param application_id The ID of your RUM Application.
  void dd_rum_config_init(
    ffi.Pointer<dd_rum_config_t> config,
    ffi.Pointer<ffi.Char> application_id,
  ) {
    return _dd_rum_config_init(
      config,
      application_id,
    );
  }

  late final _dd_rum_config_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_config_init');
  late final _dd_rum_config_init = _dd_rum_config_initPtr.asFunction<
      void Function(
          ffi.Pointer<dd_rum_config_t>, ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the RUM Application ID, overriding the value passed to dd_rum_config_init().
  void dd_rum_config_set_application_id(
    ffi.Pointer<dd_rum_config_t> config,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dd_rum_config_set_application_id(
      config,
      value,
    );
  }

  late final _dd_rum_config_set_application_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_config_t>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_config_set_application_id');
  late final _dd_rum_config_set_application_id =
      _dd_rum_config_set_application_idPtr.asFunction<
          void Function(ffi.Pointer<dd_rum_config_t>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Sets the sample rate to a value between 0.0 and 100.0, indicating what percentage of
  /// RUM sessions should be sampled. At 100.0, events for all sessions are sent to intake;
  /// at 0.0, no RUM events are generated. Default is 100.0.
  void dd_rum_config_set_session_sample_rate(
    ffi.Pointer<dd_rum_config_t> config,
    double value,
  ) {
    return _dd_rum_config_set_session_sample_rate(
      config,
      value,
    );
  }

  late final _dd_rum_config_set_session_sample_ratePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_config_t>,
              ffi.Float)>>('dd_rum_config_set_session_sample_rate');
  late final _dd_rum_config_set_session_sample_rate =
      _dd_rum_config_set_session_sample_ratePtr
          .asFunction<void Function(ffi.Pointer<dd_rum_config_t>, double)>(
              isLeaf: true);

  /// Registers the RUM feature with the core of the Datadog SDK. MUST be matched with
  /// a call to dd_rum_destroy().
  ffi.Pointer<dd_rum_t> dd_rum_init(
    ffi.Pointer<dd_core_t> core,
    ffi.Pointer<dd_rum_config_t> config,
  ) {
    return _dd_rum_init(
      core,
      config,
    );
  }

  late final _dd_rum_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dd_rum_t> Function(ffi.Pointer<dd_core_t>,
              ffi.Pointer<dd_rum_config_t>)>>('dd_rum_init');
  late final _dd_rum_init = _dd_rum_initPtr.asFunction<
      ffi.Pointer<dd_rum_t> Function(
          ffi.Pointer<dd_core_t>, ffi.Pointer<dd_rum_config_t>)>(isLeaf: true);

  /// Frees all memory allocated for the RUM feature.
  void dd_rum_destroy(
    ffi.Pointer<dd_rum_t> rum,
  ) {
    return _dd_rum_destroy(
      rum,
    );
  }

  late final _dd_rum_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_rum_t>)>>(
          'dd_rum_destroy');
  late final _dd_rum_destroy = _dd_rum_destroyPtr
      .asFunction<void Function(ffi.Pointer<dd_rum_t>)>(isLeaf: true);

  /// Adds or updates a global attribute value that will be included with all RUM events
  /// emitted hereafter.
  void dd_rum_add_attribute(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<dd_attribute_t> value,
  ) {
    return _dd_rum_add_attribute(
      rum,
      name,
      value,
    );
  }

  late final _dd_rum_add_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_rum_add_attribute');
  late final _dd_rum_add_attribute = _dd_rum_add_attributePtr.asFunction<
      void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Removes a global attribute value, if one has been previously added with the given
  /// name.
  void dd_rum_remove_attribute(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_rum_remove_attribute(
      rum,
      name,
    );
  }

  late final _dd_rum_remove_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_remove_attribute');
  late final _dd_rum_remove_attribute = _dd_rum_remove_attributePtr
      .asFunction<void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>)>(
          isLeaf: true);

  /// Explicitly stops the current RUM session, if one is active.
  ///
  /// Once a session has been explicitly stopped, the next call to dd_rum_start_view(),
  /// dd_rum_start_action(), or dd_rum_add_action() will automatically start a new session.
  /// If that new session is created in response to an action, the last active view from
  /// the previous session will be restarted in the new session.
  void dd_rum_stop_session(
    ffi.Pointer<dd_rum_t> rum,
  ) {
    return _dd_rum_stop_session(
      rum,
    );
  }

  late final _dd_rum_stop_sessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dd_rum_t>)>>(
          'dd_rum_stop_session');
  late final _dd_rum_stop_session = _dd_rum_stop_sessionPtr
      .asFunction<void Function(ffi.Pointer<dd_rum_t>)>(isLeaf: true);

  /// Starts a new RUM view, recording that the user has navigated to the portion of the
  /// application uniquely identified by the given string `key`. `name` is an optional
  /// human-readable view name to be used in the Datadog UI; if not specified, the view's
  /// key will be used as its name.
  ///
  /// If no RUM session is currently active, starting a view will implicitly create a new
  /// session.
  ///
  /// When a new view is started, all existing views are implicitly stopped.
  void dd_rum_start_view(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dd_rum_start_view(
      rum,
      key,
      name,
    );
  }

  late final _dd_rum_start_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_start_view');
  late final _dd_rum_start_view = _dd_rum_start_viewPtr.asFunction<
      void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Starts a new RUM view, associating an initial set of custom attributes with that
  /// view.
  void dd_rum_start_view_obj(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_rum_start_view_obj(
      rum,
      key,
      name,
      attributes,
    );
  }

  late final _dd_rum_start_view_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_rum_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_rum_start_view_obj');
  late final _dd_rum_start_view_obj = _dd_rum_start_view_objPtr.asFunction<
      void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Adds or updates a custom attribute value stored in the context of the current view,
  /// provided that the current view has the given key.
  ///
  /// All events produced within the context of a view will include the set of custom
  /// attributes formed from both global and view-level attributes, with view attributes
  /// taking precedence in the case of name conflicts.
  ///
  /// View attributes are scoped to the lifetime of the view and do not persist to
  /// subsequent views with the same key.
  void dd_rum_add_view_attribute(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> view_key,
    ffi.Pointer<ffi.Char> attribute_name,
    ffi.Pointer<dd_attribute_t> value,
  ) {
    return _dd_rum_add_view_attribute(
      rum,
      view_key,
      attribute_name,
      value,
    );
  }

  late final _dd_rum_add_view_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dd_rum_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_rum_add_view_attribute');
  late final _dd_rum_add_view_attribute =
      _dd_rum_add_view_attributePtr.asFunction<
          void Function(
              ffi.Pointer<dd_rum_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>(isLeaf: true);

  /// Removes any custom attribute value stored under the given name in the context of the
  /// current view, provided that the current view has the given key.
  ///
  /// If the view-level attribute being removed was shadowing a global attribute of the
  /// same name, subsequent events will once again use the global attribute value.
  void dd_rum_remove_view_attribute(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> view_key,
    ffi.Pointer<ffi.Char> attribute_name,
  ) {
    return _dd_rum_remove_view_attribute(
      rum,
      view_key,
      attribute_name,
    );
  }

  late final _dd_rum_remove_view_attributePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_remove_view_attribute');
  late final _dd_rum_remove_view_attribute =
      _dd_rum_remove_view_attributePtr.asFunction<
          void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>(isLeaf: true);

  /// Stops any active RUM views that are identified with the given key.
  void dd_rum_stop_view(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> key,
  ) {
    return _dd_rum_stop_view(
      rum,
      key,
    );
  }

  late final _dd_rum_stop_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>,
              ffi.Pointer<ffi.Char>)>>('dd_rum_stop_view');
  late final _dd_rum_stop_view = _dd_rum_stop_viewPtr
      .asFunction<void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>)>(
          isLeaf: true);

  /// Stops any active RUM views that have the given key, and includes the provided set of
  /// custom user attributes in the final event sent for that view.
  void dd_rum_stop_view_obj(
    ffi.Pointer<dd_rum_t> rum,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<dd_attribute_t> attributes,
  ) {
    return _dd_rum_stop_view_obj(
      rum,
      key,
      attributes,
    );
  }

  late final _dd_rum_stop_view_objPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<dd_attribute_t>)>>('dd_rum_stop_view_obj');
  late final _dd_rum_stop_view_obj = _dd_rum_stop_view_objPtr.asFunction<
      void Function(ffi.Pointer<dd_rum_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<dd_attribute_t>)>(isLeaf: true);
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;
typedef __gwchar_t = ffi.Int;
typedef Dart__gwchar_t = int;

final class imaxdiv_t extends ffi.Struct {
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;
}

typedef ptrdiff_t = ffi.Long;
typedef Dartptrdiff_t = int;

final class max_align_t extends ffi.Opaque {}

/// A point in time as measured by the system clock, expressed as a signed int64 count of
/// nanoseconds since the Unix epoch.
typedef dd_timestamp_t = ffi.Int64;
typedef Dartdd_timestamp_t = int;

final class dd_uuid extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> bytes;
}

typedef dd_uuid_t = dd_uuid;

enum dd_value_type_t {
  DD_VALUE_TYPE_NULL(0),
  DD_VALUE_TYPE_BOOL(1),
  DD_VALUE_TYPE_INT(2),
  DD_VALUE_TYPE_UINT(3),
  DD_VALUE_TYPE_TIMESTAMP(4),
  DD_VALUE_TYPE_DOUBLE(5),
  DD_VALUE_TYPE_UUID(6),
  DD_VALUE_TYPE_STRING(7),
  DD_VALUE_TYPE_ARRAY(8),
  DD_VALUE_TYPE_OBJECT(9);

  final int value;
  const dd_value_type_t(this.value);

  static dd_value_type_t fromValue(int value) => switch (value) {
        0 => DD_VALUE_TYPE_NULL,
        1 => DD_VALUE_TYPE_BOOL,
        2 => DD_VALUE_TYPE_INT,
        3 => DD_VALUE_TYPE_UINT,
        4 => DD_VALUE_TYPE_TIMESTAMP,
        5 => DD_VALUE_TYPE_DOUBLE,
        6 => DD_VALUE_TYPE_UUID,
        7 => DD_VALUE_TYPE_STRING,
        8 => DD_VALUE_TYPE_ARRAY,
        9 => DD_VALUE_TYPE_OBJECT,
        _ => throw ArgumentError('Unknown value for dd_value_type_t: $value'),
      };
}

final class UnnamedUnion extends ffi.Union {
  @ffi.Int64()
  external int i64;

  @ffi.Uint64()
  external int u64;

  @ffi.Double()
  external double f64;

  external ffi.Pointer<ffi.Void> ptr;
}

final class dd_attribute extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  dd_value_type_t get type => dd_value_type_t.fromValue(typeAsInt);

  external UnnamedUnion value;
}

typedef dd_attribute_t = dd_attribute;

/// Severity of a diagnostic message emitted by the SDK.
enum dd_diagnostic_level_t {
  DD_DIAGNOSTIC_LEVEL_DEBUG(0),
  DD_DIAGNOSTIC_LEVEL_STATUS(1),
  DD_DIAGNOSTIC_LEVEL_WARNING(2),
  DD_DIAGNOSTIC_LEVEL_ERROR(3);

  final int value;
  const dd_diagnostic_level_t(this.value);

  static dd_diagnostic_level_t fromValue(int value) => switch (value) {
        0 => DD_DIAGNOSTIC_LEVEL_DEBUG,
        1 => DD_DIAGNOSTIC_LEVEL_STATUS,
        2 => DD_DIAGNOSTIC_LEVEL_WARNING,
        3 => DD_DIAGNOSTIC_LEVEL_ERROR,
        _ => throw ArgumentError(
            'Unknown value for dd_diagnostic_level_t: $value'),
      };
}

/// A single message emitted by the SDK to signal an error or status update. By default,
/// diagnostic messages with a status of 'warning' or 'error' will be printed to stderr.
///
/// Use dd_core_config_set_diagnostic_threshold() to change the threshold for diagnostic
/// messages: at DD_DIAGNOSTIC_LEVEL_DEBUG, all messages will be emitted; at
/// DD_DIAGNOSTIC_LEVEL_ERROR, only errors will be emitted.
///
/// Use dd_core_config_set_diagnostic_handler() to specify how emitted messages should be
/// handled. Supply your own callback to override the default behavior of printing to
/// stderr; supply NULL to entirely suppress all diagnostic output.
final class dd_diagnostic_message extends ffi.Struct {
  @ffi.UnsignedInt()
  external int levelAsInt;

  dd_diagnostic_level_t get level =>
      dd_diagnostic_level_t.fromValue(levelAsInt);

  external ffi.Pointer<ffi.Char> text;
}

typedef dd_diagnostic_message_t = dd_diagnostic_message;
typedef dd_diagnostic_handler_tFunction = ffi.Void Function(
    ffi.Pointer<dd_diagnostic_message_t> message,
    ffi.Pointer<ffi.Void> userdata);
typedef Dartdd_diagnostic_handler_tFunction = void Function(
    ffi.Pointer<dd_diagnostic_message_t> message,
    ffi.Pointer<ffi.Void> userdata);

/// Callback function used to handle a single diagnostic message emitted by the SDK. If
/// you supply a value to dd_core_config_set_diagnostic_handler_userdata(), that value
/// will be passed as `userdata`; otherwise `userdata` will be NULL.
typedef dd_diagnostic_handler_t
    = ffi.Pointer<ffi.NativeFunction<dd_diagnostic_handler_tFunction>>;

/// Indicates whether the end user has consented to tracking, as determined by your
/// application.
enum dd_tracking_consent_t {
  DD_TRACKING_CONSENT_GRANTED(0),
  DD_TRACKING_CONSENT_NOT_GRANTED(1),
  DD_TRACKING_CONSENT_PENDING(2);

  final int value;
  const dd_tracking_consent_t(this.value);

  static dd_tracking_consent_t fromValue(int value) => switch (value) {
        0 => DD_TRACKING_CONSENT_GRANTED,
        1 => DD_TRACKING_CONSENT_NOT_GRANTED,
        2 => DD_TRACKING_CONSENT_PENDING,
        _ => throw ArgumentError(
            'Unknown value for dd_tracking_consent_t: $value'),
      };
}

/// The Datadog datacenter in which your organization's data is stored.
enum dd_site_t {
  DD_SITE_US1(0),
  DD_SITE_US3(1),
  DD_SITE_US5(2),
  DD_SITE_EU1(3),
  DD_SITE_AP1(4),
  DD_SITE_AP2(5),
  DD_SITE_US1_FED(6);

  final int value;
  const dd_site_t(this.value);

  static dd_site_t fromValue(int value) => switch (value) {
        0 => DD_SITE_US1,
        1 => DD_SITE_US3,
        2 => DD_SITE_US5,
        3 => DD_SITE_EU1,
        4 => DD_SITE_AP1,
        5 => DD_SITE_AP2,
        6 => DD_SITE_US1_FED,
        _ => throw ArgumentError('Unknown value for dd_site_t: $value'),
      };
}

/// Determines how long the SDK will accumulate events in a single batch before releasing
/// that batch to be processed in the next upload cycle.
enum dd_batch_size_t {
  DD_BATCH_SIZE_SMALL(0),
  DD_BATCH_SIZE_MEDIUM(1),
  DD_BATCH_SIZE_LARGE(2);

  final int value;
  const dd_batch_size_t(this.value);

  static dd_batch_size_t fromValue(int value) => switch (value) {
        0 => DD_BATCH_SIZE_SMALL,
        1 => DD_BATCH_SIZE_MEDIUM,
        2 => DD_BATCH_SIZE_LARGE,
        _ => throw ArgumentError('Unknown value for dd_batch_size_t: $value'),
      };
}

/// Determines how often upload cycles occur for any given feature.
enum dd_upload_frequency_t {
  DD_UPLOAD_FREQUENCY_FREQUENT(0),
  DD_UPLOAD_FREQUENCY_AVERAGE(1),
  DD_UPLOAD_FREQUENCY_RARE(2);

  final int value;
  const dd_upload_frequency_t(this.value);

  static dd_upload_frequency_t fromValue(int value) => switch (value) {
        0 => DD_UPLOAD_FREQUENCY_FREQUENT,
        1 => DD_UPLOAD_FREQUENCY_AVERAGE,
        2 => DD_UPLOAD_FREQUENCY_RARE,
        _ => throw ArgumentError(
            'Unknown value for dd_upload_frequency_t: $value'),
      };
}

/// Determines the maximum number of batches that may be processed and uploaded for a
/// given feature within a single upload cycle.
enum dd_batch_processing_level_t {
  DD_BATCH_PROCESSING_LEVEL_LOW(0),
  DD_BATCH_PROCESSING_LEVEL_MEDIUM(1),
  DD_BATCH_PROCESSING_LEVEL_HIGH(2);

  final int value;
  const dd_batch_processing_level_t(this.value);

  static dd_batch_processing_level_t fromValue(int value) => switch (value) {
        0 => DD_BATCH_PROCESSING_LEVEL_LOW,
        1 => DD_BATCH_PROCESSING_LEVEL_MEDIUM,
        2 => DD_BATCH_PROCESSING_LEVEL_HIGH,
        _ => throw ArgumentError(
            'Unknown value for dd_batch_processing_level_t: $value'),
      };
}

/// FOR INTERNAL USE ONLY - These values are not part of the public API and may change
/// without notice. Do not use in production code.
final class dd_internal_options extends ffi.Struct {
  @ffi.Bool()
  external bool flush_http_requests_on_stop;

  external ffi.Pointer<ffi.Char> custom_endpoint_url;
}

typedef dd_internal_options_t = dd_internal_options;

/// Top-level configuration options for the Datadog SDK. Initialize with
/// dd_core_config_init(), then call dd_core_config_set_<value>().
final class dd_core_config extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  external dd_diagnostic_handler_t diagnostic_handler;

  external ffi.Pointer<ffi.Void> diagnostic_handler_userdata;

  @ffi.UnsignedInt()
  external int diagnostic_thresholdAsInt;

  dd_diagnostic_level_t get diagnostic_threshold =>
      dd_diagnostic_level_t.fromValue(diagnostic_thresholdAsInt);

  @ffi.UnsignedInt()
  external int tracking_consentAsInt;

  dd_tracking_consent_t get tracking_consent =>
      dd_tracking_consent_t.fromValue(tracking_consentAsInt);

  @ffi.UnsignedInt()
  external int siteAsInt;

  dd_site_t get site => dd_site_t.fromValue(siteAsInt);

  external ffi.Pointer<ffi.Char> client_token;

  external ffi.Pointer<ffi.Char> service;

  external ffi.Pointer<ffi.Char> env;

  external ffi.Pointer<ffi.Char> application_version;

  @ffi.UnsignedInt()
  external int batch_sizeAsInt;

  dd_batch_size_t get batch_size => dd_batch_size_t.fromValue(batch_sizeAsInt);

  @ffi.UnsignedInt()
  external int upload_frequencyAsInt;

  dd_upload_frequency_t get upload_frequency =>
      dd_upload_frequency_t.fromValue(upload_frequencyAsInt);

  @ffi.UnsignedInt()
  external int batch_processing_levelAsInt;

  dd_batch_processing_level_t get batch_processing_level =>
      dd_batch_processing_level_t.fromValue(batch_processing_levelAsInt);

  external dd_internal_options_t internal_options;
}

typedef dd_core_config_t = dd_core_config;

final class dd_core extends ffi.Opaque {}

/// Top-level interface to the Datadog SDK.
///
/// Call dd_core_create() to create a new core, register your desired set of features on
/// that core (e.g. dd_logging_init(core)), and then call dd_core_start() to begin the
/// SDK's background processing.
typedef dd_core_t = dd_core;

/// Severity at which log messages may be emitted.
enum dd_log_level_t {
  DD_LOG_LEVEL_DEBUG(0),
  DD_LOG_LEVEL_INFO(1),
  DD_LOG_LEVEL_NOTICE(2),
  DD_LOG_LEVEL_WARN(3),
  DD_LOG_LEVEL_ERROR(4),
  DD_LOG_LEVEL_CRITICAL(5);

  final int value;
  const dd_log_level_t(this.value);

  static dd_log_level_t fromValue(int value) => switch (value) {
        0 => DD_LOG_LEVEL_DEBUG,
        1 => DD_LOG_LEVEL_INFO,
        2 => DD_LOG_LEVEL_NOTICE,
        3 => DD_LOG_LEVEL_WARN,
        4 => DD_LOG_LEVEL_ERROR,
        5 => DD_LOG_LEVEL_CRITICAL,
        _ => throw ArgumentError('Unknown value for dd_log_level_t: $value'),
      };
}

/// Logger configuration struct: initialize with dd_logger_config_init(), then call
/// dd_logger_config_set_<value>().
final class dd_logger_config extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  @ffi.Float()
  external double remote_sample_rate;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> service;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;

  @ffi.UnsignedInt()
  external int remote_log_thresholdAsInt;

  dd_log_level_t get remote_log_threshold =>
      dd_log_level_t.fromValue(remote_log_thresholdAsInt);

  @ffi.Size()
  external int initial_attribute_capacity;

  @ffi.Bool()
  external bool enrich_with_rum_context;
}

typedef dd_logger_config_t = dd_logger_config;

final class dd_logger extends ffi.Opaque {}

/// Interface used to emit log messages.
typedef dd_logger_t = dd_logger;

final class dd_logging extends ffi.Opaque {}

/// Interface to the Datadog SDK's logging feature. Use dd_logging_init() to register the
/// logging feature with the core. You MUST call dd_logging_destroy() when done.
typedef dd_logging_t = dd_logging;

/// RUM configuration struct: initialize with dd_rum_config_init(), then call
/// dd_rum_config_set_<value>().
final class dd_rum_config extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  external dd_uuid_t application_id;

  @ffi.Float()
  external double session_sample_rate;
}

typedef dd_rum_config_t = dd_rum_config;

final class dd_rum extends ffi.Opaque {}

/// Interface to the Datadog SDK's RUM feature. Use dd_rum_init() to register the
/// RUM feature with the core. You MUST call dd_rum_destroy() when done.
typedef dd_rum_t = dd_rum;

const int _INTTYPES_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C2X_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 39;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int _STDINT_H = 1;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;

const int ____gwchar_t_defined = 1;

const String __PRI64_PREFIX = 'l';

const String __PRIPTR_PREFIX = 'l';

const String PRId8 = 'd';

const String PRId16 = 'd';

const String PRId32 = 'd';

const String PRId64 = 'ld';

const String PRIdLEAST8 = 'd';

const String PRIdLEAST16 = 'd';

const String PRIdLEAST32 = 'd';

const String PRIdLEAST64 = 'ld';

const String PRIdFAST8 = 'd';

const String PRIdFAST16 = 'ld';

const String PRIdFAST32 = 'ld';

const String PRIdFAST64 = 'ld';

const String PRIi8 = 'i';

const String PRIi16 = 'i';

const String PRIi32 = 'i';

const String PRIi64 = 'li';

const String PRIiLEAST8 = 'i';

const String PRIiLEAST16 = 'i';

const String PRIiLEAST32 = 'i';

const String PRIiLEAST64 = 'li';

const String PRIiFAST8 = 'i';

const String PRIiFAST16 = 'li';

const String PRIiFAST32 = 'li';

const String PRIiFAST64 = 'li';

const String PRIo8 = 'o';

const String PRIo16 = 'o';

const String PRIo32 = 'o';

const String PRIo64 = 'lo';

const String PRIoLEAST8 = 'o';

const String PRIoLEAST16 = 'o';

const String PRIoLEAST32 = 'o';

const String PRIoLEAST64 = 'lo';

const String PRIoFAST8 = 'o';

const String PRIoFAST16 = 'lo';

const String PRIoFAST32 = 'lo';

const String PRIoFAST64 = 'lo';

const String PRIu8 = 'u';

const String PRIu16 = 'u';

const String PRIu32 = 'u';

const String PRIu64 = 'lu';

const String PRIuLEAST8 = 'u';

const String PRIuLEAST16 = 'u';

const String PRIuLEAST32 = 'u';

const String PRIuLEAST64 = 'lu';

const String PRIuFAST8 = 'u';

const String PRIuFAST16 = 'lu';

const String PRIuFAST32 = 'lu';

const String PRIuFAST64 = 'lu';

const String PRIx8 = 'x';

const String PRIx16 = 'x';

const String PRIx32 = 'x';

const String PRIx64 = 'lx';

const String PRIxLEAST8 = 'x';

const String PRIxLEAST16 = 'x';

const String PRIxLEAST32 = 'x';

const String PRIxLEAST64 = 'lx';

const String PRIxFAST8 = 'x';

const String PRIxFAST16 = 'lx';

const String PRIxFAST32 = 'lx';

const String PRIxFAST64 = 'lx';

const String PRIX8 = 'X';

const String PRIX16 = 'X';

const String PRIX32 = 'X';

const String PRIX64 = 'lX';

const String PRIXLEAST8 = 'X';

const String PRIXLEAST16 = 'X';

const String PRIXLEAST32 = 'X';

const String PRIXLEAST64 = 'lX';

const String PRIXFAST8 = 'X';

const String PRIXFAST16 = 'lX';

const String PRIXFAST32 = 'lX';

const String PRIXFAST64 = 'lX';

const String PRIdMAX = 'ld';

const String PRIiMAX = 'li';

const String PRIoMAX = 'lo';

const String PRIuMAX = 'lu';

const String PRIxMAX = 'lx';

const String PRIXMAX = 'lX';

const String PRIdPTR = 'ld';

const String PRIiPTR = 'li';

const String PRIoPTR = 'lo';

const String PRIuPTR = 'lu';

const String PRIxPTR = 'lx';

const String PRIXPTR = 'lX';

const String SCNd8 = 'hhd';

const String SCNd16 = 'hd';

const String SCNd32 = 'd';

const String SCNd64 = 'ld';

const String SCNdLEAST8 = 'hhd';

const String SCNdLEAST16 = 'hd';

const String SCNdLEAST32 = 'd';

const String SCNdLEAST64 = 'ld';

const String SCNdFAST8 = 'hhd';

const String SCNdFAST16 = 'ld';

const String SCNdFAST32 = 'ld';

const String SCNdFAST64 = 'ld';

const String SCNi8 = 'hhi';

const String SCNi16 = 'hi';

const String SCNi32 = 'i';

const String SCNi64 = 'li';

const String SCNiLEAST8 = 'hhi';

const String SCNiLEAST16 = 'hi';

const String SCNiLEAST32 = 'i';

const String SCNiLEAST64 = 'li';

const String SCNiFAST8 = 'hhi';

const String SCNiFAST16 = 'li';

const String SCNiFAST32 = 'li';

const String SCNiFAST64 = 'li';

const String SCNu8 = 'hhu';

const String SCNu16 = 'hu';

const String SCNu32 = 'u';

const String SCNu64 = 'lu';

const String SCNuLEAST8 = 'hhu';

const String SCNuLEAST16 = 'hu';

const String SCNuLEAST32 = 'u';

const String SCNuLEAST64 = 'lu';

const String SCNuFAST8 = 'hhu';

const String SCNuFAST16 = 'lu';

const String SCNuFAST32 = 'lu';

const String SCNuFAST64 = 'lu';

const String SCNo8 = 'hho';

const String SCNo16 = 'ho';

const String SCNo32 = 'o';

const String SCNo64 = 'lo';

const String SCNoLEAST8 = 'hho';

const String SCNoLEAST16 = 'ho';

const String SCNoLEAST32 = 'o';

const String SCNoLEAST64 = 'lo';

const String SCNoFAST8 = 'hho';

const String SCNoFAST16 = 'lo';

const String SCNoFAST32 = 'lo';

const String SCNoFAST64 = 'lo';

const String SCNx8 = 'hhx';

const String SCNx16 = 'hx';

const String SCNx32 = 'x';

const String SCNx64 = 'lx';

const String SCNxLEAST8 = 'hhx';

const String SCNxLEAST16 = 'hx';

const String SCNxLEAST32 = 'x';

const String SCNxLEAST64 = 'lx';

const String SCNxFAST8 = 'hhx';

const String SCNxFAST16 = 'lx';

const String SCNxFAST32 = 'lx';

const String SCNxFAST64 = 'lx';

const String SCNdMAX = 'ld';

const String SCNiMAX = 'li';

const String SCNoMAX = 'lo';

const String SCNuMAX = 'lu';

const String SCNxMAX = 'lx';

const String SCNdPTR = 'ld';

const String SCNiPTR = 'li';

const String SCNoPTR = 'lo';

const String SCNuPTR = 'lu';

const String SCNxPTR = 'lx';

const int __bool_true_false_are_defined = 1;

const int true$ = 1;

const int false$ = 0;

const int NULL = 0;

const int DATADOG_MAX_SERVICE_NAME_LEN = 127;

const int DATADOG_MAX_LOGGER_NAME_LEN = 63;
