name: datadog_flutter_plugin_android
description: Android implementation of the datadog_flutter_plugin package.
version: 1.0.0
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^1.0.0
  datadog_flutter_plugin_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"
  jnigen: ^0.16.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  datadog_common_test:
    path: ../../datadog_common_test

flutter:
  plugin:
    implements: datadog_flutter_plugin
    platforms:
      android:
        package: com.datadoghq.flutter
        pluginClass: DatadogSdkPlugin
        dartPluginClass: DatadogFlutterPluginAndroid
