// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// Hand-maintained plugin header. `FlutterPluginRegistrant` imports this directly
// (`#import <datadog_session_replay/DatadogSessionReplayPlugin.h>`), so the plugin
// registration symbol does NOT depend on the auto-generated Swift interface header
// (`datadog_session_replay_bridge.h`), which is regenerated by Xcode and drops the
// `<FlutterPlugin>` conformance when Flutter's protocols aren't visible.
//
// The Swift class is exported to Objective-C as `DatadogSessionReplayPlugin` via
// `@objc(DatadogSessionReplayPlugin)`, so a plain declaration suffices here.

#import <Foundation/Foundation.h>

// Forward-declare the registrar protocol so this header compiles without a full
// Flutter import. The real definition comes from Flutter.framework at link time.
// `<FlutterPlugin>` conformance is intentionally omitted: the registrant only needs
// to invoke `+registerWithRegistrar:`, and declaring conformance to a forward-declared
// protocol would emit a "cannot find protocol definition" warning.
@protocol FlutterPluginRegistrar;

@interface DatadogSessionReplayPlugin : NSObject
+ (void)registerWithRegistrar:(nonnull id<FlutterPluginRegistrar>)registrar;
@end
