name: datadog_flags_example
description: Command line examples for the Datadog Feature Flags SDK.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  args: ^2.5.0
  datadog_flags:
    path: ..

dev_dependencies:
  lints: '>=5.0.0'

executables:
  typed_evaluation:
