name: datadog_session_replay
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://www.datadoghq.com/
repository: https://github.com/DataDog/dd-sdk-flutter/packages/datadog_session_replay

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  datadog_flutter_plugin: ^2.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.datadog_session_replay
        pluginClass: DatadogSessionReplayPlugin
      ios:
        pluginClass: DatadogSessionReplayPlugin